// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:23:56.355720

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'turn_context.zorphy.dart';
part 'turn_context.g.dart';

/// TurnContext entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $TurnContext {

  String get id;
  int get turnNumber;
  List<String> get messageIds;
  DateTime get turnStartTime;
  List<String> get toolCallIds;
}

