// GENERATED - DO NOT EDIT
// Generated by zfa for: Suite
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/suite/suite.dart';
import '../../repositories/suite_repository.dart';

class GetSuiteUseCase extends UseCase<Suite, QueryParams<Suite>> {
  GetSuiteUseCase(this._repository);

  final SuiteRepository _repository;

  @override
  Future<Suite> execute(
    QueryParams<Suite> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
