// GENERATED - DO NOT EDIT
// Generated by zfa for: Suite
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/suite/suite.dart';
import '../../repositories/suite_repository.dart';

class UpdateSuiteUseCase
    extends UseCase<Suite, UpdateParams<String, SuitePatch>> {
  UpdateSuiteUseCase(this._repository);

  final SuiteRepository _repository;

  @override
  Future<Suite> execute(
    UpdateParams<String, SuitePatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
