// GENERATED - DO NOT EDIT
// Generated by zfa for: GoldenMission
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/golden_mission/golden_mission.dart';
import '../../repositories/golden_mission_repository.dart';

class GetGoldenMissionUseCase
    extends UseCase<GoldenMission, QueryParams<GoldenMission>> {
  GetGoldenMissionUseCase(this._repository);

  final GoldenMissionRepository _repository;

  @override
  Future<GoldenMission> execute(
    QueryParams<GoldenMission> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
