// GENERATED - DO NOT EDIT
// Generated by zfa for: GoldenMission
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/golden_mission/golden_mission.dart';
import '../../repositories/golden_mission_repository.dart';

class UpdateGoldenMissionUseCase
    extends UseCase<GoldenMission, UpdateParams<String, GoldenMissionPatch>> {
  UpdateGoldenMissionUseCase(this._repository);

  final GoldenMissionRepository _repository;

  @override
  Future<GoldenMission> execute(
    UpdateParams<String, GoldenMissionPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
