// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:41.599797

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'thinking_level_change_entry.zorphy.dart';
part 'thinking_level_change_entry.g.dart';

/// ThinkingLevelChangeEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ThinkingLevelChangeEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get thinkingLevel;
}

