// GENERATED - DO NOT EDIT
// Generated by zfa for: AbortMission
import 'package:zuraffa/zuraffa.dart';

import '../../services/engine_loop_service.dart';

class AbortMissionUseCase extends UseCase<void, NoParams> {
  AbortMissionUseCase(this._engineLoopService);

  final EngineLoopService _engineLoopService;

  @override
  Future<void> execute(
    NoParams params, [
    CancelToken? cancelToken,
  ]) async {
    cancelToken?.throwIfCancelled();
    return await _engineLoopService.abortMission(params);
  }
}

// END GENERATED