// GENERATED - DO NOT EDIT
// Generated by zfa for: EvaluateSuite
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/suite/suite.dart';
import '../../services/suite_service.dart';

class EvaluateSuiteUseCase extends SyncUseCase<void, Suite> {
  EvaluateSuiteUseCase(this._suiteService);

  final SuiteService _suiteService;

  @override
  void execute(Suite params) => _suiteService.evaluate(params);
}

// END GENERATED