// GENERATED - DO NOT EDIT
// Generated by zfa for: ExecuteMission
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/mission_config/mission_config.dart';
import '../../services/engine_loop_service.dart';

class ExecuteMissionUseCase extends UseCase<void, MissionConfig> {
  ExecuteMissionUseCase(this._engineLoopService);

  final EngineLoopService _engineLoopService;

  @override
  Future<void> execute(
    MissionConfig params, [
    CancelToken? cancelToken,
  ]) async {
    cancelToken?.throwIfCancelled();
    return await _engineLoopService.executeMission(params);
  }
}

// END GENERATED