// GENERATED - DO NOT EDIT
// Generated by zfa for: ExecuteSubAgent
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/sub_agent_type/sub_agent_type.dart';
import '../../services/sub_agent_type_service.dart';

class ExecuteSubAgentUseCase extends SyncUseCase<void, SubAgentType> {
  ExecuteSubAgentUseCase(this._subAgentTypeService);

  final SubAgentTypeService _subAgentTypeService;

  @override
  void execute(SubAgentType params) => _subAgentTypeService.execute(params);
}

// END GENERATED