// GENERATED - DO NOT EDIT
// Generated by zfa for: GetTool
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_tool/agent_tool.dart';
import '../../services/agent_tool_service.dart';

class GetToolUseCase extends UseCase<AgentTool, String> {
  GetToolUseCase(this._agentToolService);

  final AgentToolService _agentToolService;

  @override
  Future<AgentTool> execute(String params, [CancelToken? cancelToken]) async {
    cancelToken?.throwIfCancelled();
    return _agentToolService.getTool(params);
  }
}

// END GENERATED
