// GENERATED - DO NOT EDIT
// Generated by zfa for: InjectSteering
import 'package:zuraffa/zuraffa.dart';

import '../../services/engine_loop_service.dart';

class InjectSteeringUseCase extends SyncUseCase<void, String> {
  InjectSteeringUseCase(this._engineLoopService);

  final EngineLoopService _engineLoopService;

  @override
  void execute(String params) => _engineLoopService.injectSteering(params);
}

// END GENERATED
