// GENERATED - DO NOT EDIT
// Generated by zfa for: IsHealthy
import 'package:zuraffa/zuraffa.dart';

import '../../services/client_health_service.dart';

class IsHealthyUseCase extends UseCase<bool, String> {
  IsHealthyUseCase(this._clientHealthService);

  final ClientHealthService _clientHealthService;

  @override
  Future<bool> execute(String params, [CancelToken? cancelToken]) async {
    cancelToken?.throwIfCancelled();
    return _clientHealthService.isHealthy(params);
  }
}

// END GENERATED
