// GENERATED - DO NOT EDIT
// Generated by zfa for: ListTools
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_tool/agent_tool.dart';
import '../../services/agent_tool_service.dart';

class ListToolsUseCase extends UseCase<List<AgentTool>, NoParams> {
  ListToolsUseCase(this._agentToolService);

  final AgentToolService _agentToolService;

  @override
  Future<List<AgentTool>> execute(
    NoParams params, [
    CancelToken? cancelToken,
  ]) async {
    cancelToken?.throwIfCancelled();
    return await _agentToolService.listTools();
  }
}

// END GENERATED