// GENERATED - DO NOT EDIT
// Generated by zfa for: MarkFailure
import 'package:zuraffa/zuraffa.dart';

import '../../services/client_health_service.dart';

class MarkFailureUseCase extends SyncUseCase<void, String> {
  MarkFailureUseCase(this._clientHealthService);

  final ClientHealthService _clientHealthService;

  @override
  void execute(String params) => _clientHealthService.markFailure(params);
}

// END GENERATED
