// GENERATED - DO NOT EDIT
// Generated by zfa for: RecordGoldenMission
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/golden_mission/golden_mission.dart';
import '../../services/golden_mission_service.dart';

class RecordGoldenMissionUseCase extends SyncUseCase<void, GoldenMission> {
  RecordGoldenMissionUseCase(this._goldenMissionService);

  final GoldenMissionService _goldenMissionService;

  @override
  void execute(GoldenMission params) => _goldenMissionService.record(params);
}

// END GENERATED