// GENERATED - DO NOT EDIT
// Generated by zfa for: RecordFailure
import 'package:zuraffa/zuraffa.dart';

import '../../services/fallback_chain_service.dart';

class RecordFailureUseCase extends SyncUseCase<void, String> {
  RecordFailureUseCase(this._fallbackChainService);

  final FallbackChainService _fallbackChainService;

  @override
  void execute(String params) => _fallbackChainService.recordFailure(params);
}

// END GENERATED
