// GENERATED - DO NOT EDIT
// Generated by zfa for: ReplayGoldenMission
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/golden_mission/golden_mission.dart';
import '../../services/golden_mission_service.dart';

class ReplayGoldenMissionUseCase extends SyncUseCase<void, GoldenMission> {
  ReplayGoldenMissionUseCase(this._goldenMissionService);

  final GoldenMissionService _goldenMissionService;

  @override
  void execute(GoldenMission params) => _goldenMissionService.replay(params);
}

// END GENERATED