// GENERATED - DO NOT EDIT
// Generated by zfa for: ResolveAgentSpec
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_spec/agent_spec.dart';
import '../../services/agent_spec_service.dart';

class ResolveAgentSpecUseCase extends UseCase<AgentSpec, String> {
  ResolveAgentSpecUseCase(this._agentSpecService);

  final AgentSpecService _agentSpecService;

  @override
  Future<AgentSpec> execute(String params, [CancelToken? cancelToken]) async {
    cancelToken?.throwIfCancelled();
    return await _agentSpecService.resolve(params);
  }
}

// END GENERATED