// GENERATED - DO NOT EDIT
// Generated by zfa for: ScoreSuite
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/suite/suite.dart';
import '../../services/suite_service.dart';

class ScoreSuiteUseCase extends UseCase<double, Suite> {
  ScoreSuiteUseCase(this._suiteService);

  final SuiteService _suiteService;

  @override
  Future<double> execute(Suite params, [CancelToken? cancelToken]) async {
    cancelToken?.throwIfCancelled();
    return await _suiteService.score(params);
  }
}

// END GENERATED