// GENERATED - DO NOT EDIT
// Generated by zfa for: SelectProvider
import 'package:zuraffa/zuraffa.dart';

import '../../services/fallback_chain_service.dart';

class SelectProviderUseCase extends UseCase<String, NoParams> {
  SelectProviderUseCase(this._fallbackChainService);

  final FallbackChainService _fallbackChainService;

  @override
  Future<String> execute(NoParams params, [CancelToken? cancelToken]) async {
    cancelToken?.throwIfCancelled();
    return await _fallbackChainService.selectProvider();
  }
}

// END GENERATED