// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:23:56.192399

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'stop_policy.zorphy.dart';
part 'stop_policy.g.dart';

/// StopPolicy entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $StopPolicy {

  String get id;
  int get maxTurns;
  int get wallClockTimeoutMs;
  int get repetitionThreshold;
  bool get enabled;
}

