// GENERATED - DO NOT EDIT
// Generated by zfa for: ApprovalRequest
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/approval_request/approval_request.dart';
import '../../mock/approval_request_mock_data.dart';
import 'approval_request_datasource.dart';

/// Mock data source for ApprovalRequest
class ApprovalRequestMockDataSource
    with Loggable, FailureHandler
    implements ApprovalRequestDataSource {
  ApprovalRequestMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ApprovalRequest> get(QueryParams<ApprovalRequest> params) async {
    logger.info('Getting ApprovalRequest with params: $params');
    await Future<void>.delayed(_delay);
    final item = ApprovalRequestMockData.approvalRequests.query(params);
    logger.info('Successfully retrieved ApprovalRequest');
    return item;
  }

  @override
  Future<ApprovalRequest> update(
    UpdateParams<String, ApprovalRequestPatch> params,
  ) async {
    logger.info('Updating ApprovalRequest: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = ApprovalRequestMockData.sampleApprovalRequest;
    logger.info('Successfully updated ApprovalRequest');
    return existing;
  }

  @override
  Future<ApprovalRequest> toggle(
    ToggleParams<String, Field<ApprovalRequest, dynamic>> params,
  ) async {
    logger.info(
      'Toggling ApprovalRequest: ${params.id} on field ${params.field}',
    );
    await Future<void>.delayed(_delay);
    final existing = ApprovalRequestMockData.sampleApprovalRequest;
    logger.info('Successfully toggled ApprovalRequest');
    return existing;
  }
}

// END GENERATED
