// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:23:56.315045

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'mission_config.zorphy.dart';
part 'mission_config.g.dart';

/// MissionConfig entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $MissionConfig {

  String get id;
  String get missionId;
  String get initialPrompt;
  List<String> get availableTools;
  Map<String, dynamic> get metadata;
}

