// GENERATED - DO NOT EDIT
// Generated by zfa for: Artifact
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact/artifact.dart';
import '../../mock/artifact_mock_data.dart';
import 'artifact_datasource.dart';

/// Mock data source for Artifact
class ArtifactMockDataSource
    with Loggable, FailureHandler
    implements ArtifactDataSource {
  ArtifactMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<Artifact> get(QueryParams<Artifact> params) async {
    logger.info('Getting Artifact with params: $params');
    await Future<void>.delayed(_delay);
    final item = ArtifactMockData.artifacts.query(params);
    logger.info('Successfully retrieved Artifact');
    return item;
  }

  @override
  Future<Artifact> update(UpdateParams<String, ArtifactPatch> params) async {
    logger.info('Updating Artifact: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = ArtifactMockData.sampleArtifact;
    logger.info('Successfully updated Artifact');
    return existing;
  }

  @override
  Future<Artifact> toggle(
    ToggleParams<String, Field<Artifact, dynamic>> params,
  ) async {
    logger.info('Toggling Artifact: ${params.id} on field ${params.field}');
    await Future<void>.delayed(_delay);
    final existing = ArtifactMockData.sampleArtifact;
    logger.info('Successfully toggled Artifact');
    return existing;
  }
}

// END GENERATED
