// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:38:06.865816

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'sub_agent_type.zorphy.dart';
part 'sub_agent_type.g.dart';

/// SubAgentType entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $SubAgentType {

  String get id;
  String get name;
  String get specRef;
  List<String> get allowlist;
  String get budgetProfile;
}

