// GENERATED - DO NOT EDIT
// Generated by zfa for: StoreParams
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/store_params/store_params.dart';
import '../../repositories/store_params_repository.dart';

class GetStoreParamsUseCase
    extends UseCase<StoreParams, QueryParams<StoreParams>> {
  GetStoreParamsUseCase(this._repository);

  final StoreParamsRepository _repository;

  @override
  Future<StoreParams> execute(
    QueryParams<StoreParams> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
