// GENERATED - DO NOT EDIT
// Generated by zfa for: StoreParams
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/store_params/store_params.dart';
import '../../repositories/store_params_repository.dart';

class UpdateStoreParamsUseCase
    extends UseCase<StoreParams, UpdateParams<String, StoreParamsPatch>> {
  UpdateStoreParamsUseCase(this._repository);

  final StoreParamsRepository _repository;

  @override
  Future<StoreParams> execute(
    UpdateParams<String, StoreParamsPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
