// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:23:56.232897

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'repetition_tracker.zorphy.dart';
part 'repetition_tracker.g.dart';

/// RepetitionTracker entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $RepetitionTracker {

  String get id;
  Map<String, int> get callSignatures;
  List<String> get recentCalls;
}

