// GENERATED - DO NOT EDIT
// Generated by zfa for: LabelEntry
// zfa make LabelEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/label_entry/label_entry.dart';
import '../../domain/repositories/label_entry_repository.dart';
import '../datasources/label_entry/label_entry_datasource.dart';

class DataLabelEntryRepository
    with Loggable, FailureHandler
    implements LabelEntryRepository {
  DataLabelEntryRepository(this._dataSource);

  final LabelEntryDataSource _dataSource;

  @override
  Future<LabelEntry> get(QueryParams<LabelEntry> params) {
    return _dataSource.get(params);
  }

  @override
  Future<LabelEntry> update(UpdateParams<String, LabelEntryPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
