// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentSpec
// zfa make AgentSpec --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/agent_spec/agent_spec.dart';
import '../../domain/repositories/agent_spec_repository.dart';
import '../datasources/agent_spec/agent_spec_datasource.dart';

class DataAgentSpecRepository
    with Loggable, FailureHandler
    implements AgentSpecRepository {
  DataAgentSpecRepository(this._dataSource);

  final AgentSpecDataSource _dataSource;

  @override
  Future<AgentSpec> get(QueryParams<AgentSpec> params) {
    return _dataSource.get(params);
  }

  @override
  Future<AgentSpec> update(UpdateParams<String, AgentSpecPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
