// GENERATED - DO NOT EDIT
// Generated by zfa for: GoldenMission
// zfa make GoldenMission --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/golden_mission/golden_mission.dart';
import '../../domain/repositories/golden_mission_repository.dart';
import '../datasources/golden_mission/golden_mission_datasource.dart';

class DataGoldenMissionRepository
    with Loggable, FailureHandler
    implements GoldenMissionRepository {
  DataGoldenMissionRepository(this._dataSource);

  final GoldenMissionDataSource _dataSource;

  @override
  Future<GoldenMission> get(QueryParams<GoldenMission> params) {
    return _dataSource.get(params);
  }

  @override
  Future<GoldenMission> update(
    UpdateParams<String, GoldenMissionPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
