// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
// zfa make UsageLedgerEntry --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/usage_ledger_entry/usage_ledger_entry.dart';
import '../../domain/repositories/usage_ledger_entry_repository.dart';
import '../datasources/usage_ledger_entry/usage_ledger_entry_datasource.dart';

class DataUsageLedgerEntryRepository
    with Loggable, FailureHandler
    implements UsageLedgerEntryRepository {
  DataUsageLedgerEntryRepository(this._dataSource);

  final UsageLedgerEntryDataSource _dataSource;

  @override
  Future<UsageLedgerEntry> get(QueryParams<UsageLedgerEntry> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<UsageLedgerEntry>> getList(
    ListQueryParams<UsageLedgerEntry> params,
  ) {
    return _dataSource.getList(params);
  }

  @override
  Future<UsageLedgerEntry> create(UsageLedgerEntry usageLedgerEntry) {
    return _dataSource.create(usageLedgerEntry);
  }

  @override
  Future<UsageLedgerEntry> update(
    UpdateParams<String, UsageLedgerEntryPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<void> delete(DeleteParams<String> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
