// GENERATED - DO NOT EDIT
// Generated by zfa for: ThinkingLevelChangeEntry
// zfa make ThinkingLevelChangeEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/thinking_level_change_entry/thinking_level_change_entry.dart';
import '../../domain/repositories/thinking_level_change_entry_repository.dart';
import '../datasources/thinking_level_change_entry/thinking_level_change_entry_datasource.dart';

class DataThinkingLevelChangeEntryRepository
    with Loggable, FailureHandler
    implements ThinkingLevelChangeEntryRepository {
  DataThinkingLevelChangeEntryRepository(this._dataSource);

  final ThinkingLevelChangeEntryDataSource _dataSource;

  @override
  Future<ThinkingLevelChangeEntry> get(
    QueryParams<ThinkingLevelChangeEntry> params,
  ) {
    return _dataSource.get(params);
  }

  @override
  Future<ThinkingLevelChangeEntry> update(
    UpdateParams<String, ThinkingLevelChangeEntryPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
