// GENERATED - DO NOT EDIT
// Generated by zfa for: ClientHealth
// zfa make ClientHealth --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/client_health/client_health.dart';
import '../../domain/repositories/client_health_repository.dart';
import '../datasources/client_health/client_health_datasource.dart';

class DataClientHealthRepository
    with Loggable, FailureHandler
    implements ClientHealthRepository {
  DataClientHealthRepository(this._dataSource);

  final ClientHealthDataSource _dataSource;

  @override
  Future<ClientHealth> get(QueryParams<ClientHealth> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ClientHealth> update(UpdateParams<String, ClientHealthPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
