// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomEntry
// zfa make CustomEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/custom_entry/custom_entry.dart';
import '../../domain/repositories/custom_entry_repository.dart';
import '../datasources/custom_entry/custom_entry_datasource.dart';

class DataCustomEntryRepository
    with Loggable, FailureHandler
    implements CustomEntryRepository {
  DataCustomEntryRepository(this._dataSource);

  final CustomEntryDataSource _dataSource;

  @override
  Future<CustomEntry> get(QueryParams<CustomEntry> params) {
    return _dataSource.get(params);
  }

  @override
  Future<CustomEntry> update(UpdateParams<String, CustomEntryPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
