// GENERATED - DO NOT EDIT
// Generated by zfa for: ApprovalRequest
// zfa make ApprovalRequest --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/approval_request/approval_request.dart';
import '../../domain/repositories/approval_request_repository.dart';
import '../datasources/approval_request/approval_request_datasource.dart';

class DataApprovalRequestRepository
    with Loggable, FailureHandler
    implements ApprovalRequestRepository {
  DataApprovalRequestRepository(this._dataSource);

  final ApprovalRequestDataSource _dataSource;

  @override
  Future<ApprovalRequest> get(QueryParams<ApprovalRequest> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ApprovalRequest> update(
    UpdateParams<String, ApprovalRequestPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<ApprovalRequest> toggle(
    ToggleParams<String, Field<ApprovalRequest, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
