// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
// zfa make ArtifactRef --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/artifact_ref/artifact_ref.dart';
import '../../domain/repositories/artifact_ref_repository.dart';
import '../datasources/artifact_ref/artifact_ref_datasource.dart';

class DataArtifactRefRepository
    with Loggable, FailureHandler
    implements ArtifactRefRepository {
  DataArtifactRefRepository(this._dataSource);

  final ArtifactRefDataSource _dataSource;

  @override
  Future<ArtifactRef> get(QueryParams<ArtifactRef> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ArtifactRef> update(UpdateParams<String, ArtifactRefPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<ArtifactRef> toggle(
    ToggleParams<String, Field<ArtifactRef, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
