// GENERATED - DO NOT EDIT
// Generated by zfa for: SubAgentType
// zfa make SubAgentType --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/sub_agent_type/sub_agent_type.dart';
import '../../domain/repositories/sub_agent_type_repository.dart';
import '../datasources/sub_agent_type/sub_agent_type_datasource.dart';

class DataSubAgentTypeRepository
    with Loggable, FailureHandler
    implements SubAgentTypeRepository {
  DataSubAgentTypeRepository(this._dataSource);

  final SubAgentTypeDataSource _dataSource;

  @override
  Future<SubAgentType> get(QueryParams<SubAgentType> params) {
    return _dataSource.get(params);
  }

  @override
  Future<SubAgentType> update(UpdateParams<String, SubAgentTypePatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
