// GENERATED - DO NOT EDIT
// Generated by zfa for: EngineEvent
// zfa make EngineEvent --methods=get --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/engine_event/engine_event.dart';
import '../../domain/repositories/engine_event_repository.dart';
import '../datasources/engine_event/engine_event_datasource.dart';

class DataEngineEventRepository
    with Loggable, FailureHandler
    implements EngineEventRepository {
  DataEngineEventRepository(this._dataSource);

  final EngineEventDataSource _dataSource;

  @override
  Future<EngineEvent> get(QueryParams<EngineEvent> params) {
    return _dataSource.get(params);
  }
}

// END GENERATED
