// GENERATED - DO NOT EDIT
// Generated by zfa for: FallbackChain
// zfa make FallbackChain --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/fallback_chain/fallback_chain.dart';
import '../../domain/repositories/fallback_chain_repository.dart';
import '../datasources/fallback_chain/fallback_chain_datasource.dart';

class DataFallbackChainRepository
    with Loggable, FailureHandler
    implements FallbackChainRepository {
  DataFallbackChainRepository(this._dataSource);

  final FallbackChainDataSource _dataSource;

  @override
  Future<FallbackChain> get(QueryParams<FallbackChain> params) {
    return _dataSource.get(params);
  }

  @override
  Future<FallbackChain> update(
    UpdateParams<String, FallbackChainPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
