// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnRecord
// zfa make TurnRecord --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/turn_record/turn_record.dart';
import '../../domain/repositories/turn_record_repository.dart';
import '../datasources/turn_record/turn_record_datasource.dart';

class DataTurnRecordRepository
    with Loggable, FailureHandler
    implements TurnRecordRepository {
  DataTurnRecordRepository(this._dataSource);

  final TurnRecordDataSource _dataSource;

  @override
  Future<TurnRecord> get(QueryParams<TurnRecord> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<TurnRecord>> getList(ListQueryParams<TurnRecord> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<TurnRecord> create(TurnRecord turnRecord) {
    return _dataSource.create(turnRecord);
  }

  @override
  Future<TurnRecord> update(UpdateParams<String, TurnRecordPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<void> delete(DeleteParams<String> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
