// GENERATED - DO NOT EDIT
// Generated by zfa for: Artifact
// zfa make Artifact --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/artifact/artifact.dart';
import '../../domain/repositories/artifact_repository.dart';
import '../datasources/artifact/artifact_datasource.dart';

class DataArtifactRepository
    with Loggable, FailureHandler
    implements ArtifactRepository {
  DataArtifactRepository(this._dataSource);

  final ArtifactDataSource _dataSource;

  @override
  Future<Artifact> get(QueryParams<Artifact> params) {
    return _dataSource.get(params);
  }

  @override
  Future<Artifact> update(UpdateParams<String, ArtifactPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<Artifact> toggle(
    ToggleParams<String, Field<Artifact, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
