// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
// zfa make AgentTool --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/agent_tool/agent_tool.dart';
import '../../domain/repositories/agent_tool_repository.dart';
import '../datasources/agent_tool/agent_tool_datasource.dart';

class DataAgentToolRepository
    with Loggable, FailureHandler
    implements AgentToolRepository {
  DataAgentToolRepository(this._dataSource);

  final AgentToolDataSource _dataSource;

  @override
  Future<AgentTool> get(QueryParams<AgentTool> params) {
    return _dataSource.get(params);
  }

  @override
  Future<AgentTool> update(UpdateParams<String, AgentToolPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<AgentTool> toggle(
    ToggleParams<String, Field<AgentTool, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
