// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolCallSignature
// zfa make ToolCallSignature --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/tool_call_signature/tool_call_signature.dart';
import '../../domain/repositories/tool_call_signature_repository.dart';
import '../datasources/tool_call_signature/tool_call_signature_datasource.dart';

class DataToolCallSignatureRepository
    with Loggable, FailureHandler
    implements ToolCallSignatureRepository {
  DataToolCallSignatureRepository(this._dataSource);

  final ToolCallSignatureDataSource _dataSource;

  @override
  Future<ToolCallSignature> get(QueryParams<ToolCallSignature> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ToolCallSignature> update(
    UpdateParams<String, ToolCallSignaturePatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
