// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionSummary
// zfa make CompactionSummary --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/compaction_summary/compaction_summary.dart';
import '../../domain/repositories/compaction_summary_repository.dart';
import '../datasources/compaction_summary/compaction_summary_datasource.dart';

class DataCompactionSummaryRepository
    with Loggable, FailureHandler
    implements CompactionSummaryRepository {
  DataCompactionSummaryRepository(this._dataSource);

  final CompactionSummaryDataSource _dataSource;

  @override
  Future<CompactionSummary> get(QueryParams<CompactionSummary> params) {
    return _dataSource.get(params);
  }

  @override
  Future<CompactionSummary> update(
    UpdateParams<String, CompactionSummaryPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
