// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
// zfa make ToolInvocationRecord --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/tool_invocation_record/tool_invocation_record.dart';
import '../../domain/repositories/tool_invocation_record_repository.dart';
import '../datasources/tool_invocation_record/tool_invocation_record_datasource.dart';

class DataToolInvocationRecordRepository
    with Loggable, FailureHandler
    implements ToolInvocationRecordRepository {
  DataToolInvocationRecordRepository(this._dataSource);

  final ToolInvocationRecordDataSource _dataSource;

  @override
  Future<ToolInvocationRecord> get(QueryParams<ToolInvocationRecord> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<ToolInvocationRecord>> getList(
    ListQueryParams<ToolInvocationRecord> params,
  ) {
    return _dataSource.getList(params);
  }

  @override
  Future<ToolInvocationRecord> create(
    ToolInvocationRecord toolInvocationRecord,
  ) {
    return _dataSource.create(toolInvocationRecord);
  }

  @override
  Future<ToolInvocationRecord> update(
    UpdateParams<String, ToolInvocationRecordPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<void> delete(DeleteParams<String> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
