// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactServiceConfig
// zfa make ArtifactServiceConfig --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/artifact_service_config/artifact_service_config.dart';
import '../../domain/repositories/artifact_service_config_repository.dart';
import '../datasources/artifact_service_config/artifact_service_config_datasource.dart';

class DataArtifactServiceConfigRepository
    with Loggable, FailureHandler
    implements ArtifactServiceConfigRepository {
  DataArtifactServiceConfigRepository(this._dataSource);

  final ArtifactServiceConfigDataSource _dataSource;

  @override
  Future<ArtifactServiceConfig> get(QueryParams<ArtifactServiceConfig> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ArtifactServiceConfig> update(
    UpdateParams<String, ArtifactServiceConfigPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
