// GENERATED - DO NOT EDIT
// Generated by zfa for: Suite
// zfa make Suite --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/suite/suite.dart';
import '../../domain/repositories/suite_repository.dart';
import '../datasources/suite/suite_datasource.dart';

class DataSuiteRepository
    with Loggable, FailureHandler
    implements SuiteRepository {
  DataSuiteRepository(this._dataSource);

  final SuiteDataSource _dataSource;

  @override
  Future<Suite> get(QueryParams<Suite> params) {
    return _dataSource.get(params);
  }

  @override
  Future<Suite> update(UpdateParams<String, SuitePatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
