// GENERATED - DO NOT EDIT
// Generated by zfa for: DispatchTool
// zfa make DispatchTool --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/dispatch_tool/dispatch_tool.dart';
import '../../domain/repositories/dispatch_tool_repository.dart';
import '../datasources/dispatch_tool/dispatch_tool_datasource.dart';

class DataDispatchToolRepository
    with Loggable, FailureHandler
    implements DispatchToolRepository {
  DataDispatchToolRepository(this._dataSource);

  final DispatchToolDataSource _dataSource;

  @override
  Future<DispatchTool> get(QueryParams<DispatchTool> params) {
    return _dataSource.get(params);
  }

  @override
  Future<DispatchTool> update(UpdateParams<String, DispatchToolPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
