// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionEntry
// zfa make CompactionEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/compaction_entry/compaction_entry.dart';
import '../../domain/repositories/compaction_entry_repository.dart';
import '../datasources/compaction_entry/compaction_entry_datasource.dart';

class DataCompactionEntryRepository
    with Loggable, FailureHandler
    implements CompactionEntryRepository {
  DataCompactionEntryRepository(this._dataSource);

  final CompactionEntryDataSource _dataSource;

  @override
  Future<CompactionEntry> get(QueryParams<CompactionEntry> params) {
    return _dataSource.get(params);
  }

  @override
  Future<CompactionEntry> update(
    UpdateParams<String, CompactionEntryPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
