// GENERATED - DO NOT EDIT
// Generated by zfa for: ModelChangeEntry
// zfa make ModelChangeEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/model_change_entry/model_change_entry.dart';
import '../../domain/repositories/model_change_entry_repository.dart';
import '../datasources/model_change_entry/model_change_entry_datasource.dart';

class DataModelChangeEntryRepository
    with Loggable, FailureHandler
    implements ModelChangeEntryRepository {
  DataModelChangeEntryRepository(this._dataSource);

  final ModelChangeEntryDataSource _dataSource;

  @override
  Future<ModelChangeEntry> get(QueryParams<ModelChangeEntry> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ModelChangeEntry> update(
    UpdateParams<String, ModelChangeEntryPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
