// GENERATED - DO NOT EDIT
// Generated by zfa for: StopPolicy
// zfa make StopPolicy --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/repositories/stop_policy_repository.dart';
import '../../domain/entities/stop_policy/stop_policy.dart';
import '../datasources/stop_policy/stop_policy_datasource.dart';

class DataStopPolicyRepository
    with Loggable, FailureHandler
    implements StopPolicyRepository {
  DataStopPolicyRepository(this._dataSource);

  final StopPolicyDataSource _dataSource;

  @override
  Future<StopPolicy> get(QueryParams<StopPolicy> params) {
    return _dataSource.get(params);
  }

  @override
  Future<StopPolicy> update(UpdateParams<String, StopPolicyPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
