// GENERATED - DO NOT EDIT
// Generated by zfa for: RepetitionTracker
// zfa make RepetitionTracker --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/repetition_tracker/repetition_tracker.dart';
import '../../domain/repositories/repetition_tracker_repository.dart';
import '../datasources/repetition_tracker/repetition_tracker_datasource.dart';

class DataRepetitionTrackerRepository
    with Loggable, FailureHandler
    implements RepetitionTrackerRepository {
  DataRepetitionTrackerRepository(this._dataSource);

  final RepetitionTrackerDataSource _dataSource;

  @override
  Future<RepetitionTracker> get(QueryParams<RepetitionTracker> params) {
    return _dataSource.get(params);
  }

  @override
  Future<RepetitionTracker> update(
    UpdateParams<String, RepetitionTrackerPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
