// GENERATED - DO NOT EDIT
// Generated by zfa for: BranchSummaryEntry
// zfa make BranchSummaryEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/branch_summary_entry/branch_summary_entry.dart';
import '../../domain/repositories/branch_summary_entry_repository.dart';
import '../datasources/branch_summary_entry/branch_summary_entry_datasource.dart';

class DataBranchSummaryEntryRepository
    with Loggable, FailureHandler
    implements BranchSummaryEntryRepository {
  DataBranchSummaryEntryRepository(this._dataSource);

  final BranchSummaryEntryDataSource _dataSource;

  @override
  Future<BranchSummaryEntry> get(QueryParams<BranchSummaryEntry> params) {
    return _dataSource.get(params);
  }

  @override
  Future<BranchSummaryEntry> update(
    UpdateParams<String, BranchSummaryEntryPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
