// GENERATED - DO NOT EDIT
// Generated by zfa for: Enums
// zfa make Enums --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/enums/enums.dart';
import '../../domain/repositories/enums_repository.dart';
import '../datasources/enums/enums_datasource.dart';

class DataEnumsRepository
    with Loggable, FailureHandler
    implements EnumsRepository {
  DataEnumsRepository(this._dataSource);

  final EnumsDataSource _dataSource;

  @override
  Future<Enums> get(QueryParams<Enums> params) {
    return _dataSource.get(params);
  }

  @override
  Future<Enums> update(UpdateParams<String, EnumsPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
