// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnContext
// zfa make TurnContext --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/turn_context/turn_context.dart';
import '../../domain/repositories/turn_context_repository.dart';
import '../datasources/turn_context/turn_context_datasource.dart';

class DataTurnContextRepository
    with Loggable, FailureHandler
    implements TurnContextRepository {
  DataTurnContextRepository(this._dataSource);

  final TurnContextDataSource _dataSource;

  @override
  Future<TurnContext> get(QueryParams<TurnContext> params) {
    return _dataSource.get(params);
  }

  @override
  Future<TurnContext> update(UpdateParams<String, TurnContextPatch> params) {
    return _dataSource.update(params);
  }
}

// END GENERATED
