// GENERATED - DO NOT EDIT
// Generated by zfa for: MissionConfig
// zfa make MissionConfig --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/mission_config/mission_config.dart';
import '../../domain/repositories/mission_config_repository.dart';
import '../datasources/mission_config/mission_config_datasource.dart';

class DataMissionConfigRepository
    with Loggable, FailureHandler
    implements MissionConfigRepository {
  DataMissionConfigRepository(this._dataSource);

  final MissionConfigDataSource _dataSource;

  @override
  Future<MissionConfig> get(QueryParams<MissionConfig> params) {
    return _dataSource.get(params);
  }

  @override
  Future<MissionConfig> update(
    UpdateParams<String, MissionConfigPatch> params,
  ) {
    return _dataSource.update(params);
  }
}

// END GENERATED
