// Auto-generated by Zorphy
// Generated at: 2026-08-20T16:53:40.001951

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'store_params.zorphy.dart';
part 'store_params.g.dart';

/// StoreParams entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $StoreParams {

  List<int> get data;
  String get mimeType;
}

