// GENERATED - DO NOT EDIT
// Generated by zfa for: Enums
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/enums/enums.dart';
import '../../repositories/enums_repository.dart';

class GetEnumsUseCase extends UseCase<Enums, QueryParams<Enums>> {
  GetEnumsUseCase(this._repository);

  final EnumsRepository _repository;

  @override
  Future<Enums> execute(
    QueryParams<Enums> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
