// GENERATED - DO NOT EDIT
// Generated by zfa for: Enums
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/enums/enums.dart';
import '../../repositories/enums_repository.dart';

class UpdateEnumsUseCase
    extends UseCase<Enums, UpdateParams<String, EnumsPatch>> {
  UpdateEnumsUseCase(this._repository);

  final EnumsRepository _repository;

  @override
  Future<Enums> execute(
    UpdateParams<String, EnumsPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
