// GENERATED - DO NOT EDIT
// Generated by zfa for: StopPolicy
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/stop_policy/stop_policy.dart';
import '../../repositories/stop_policy_repository.dart';

class GetStopPolicyUseCase
    extends UseCase<StopPolicy, QueryParams<StopPolicy>> {
  GetStopPolicyUseCase(this._repository);

  final StopPolicyRepository _repository;

  @override
  Future<StopPolicy> execute(
    QueryParams<StopPolicy> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
