// GENERATED - DO NOT EDIT
// Generated by zfa for: StopPolicy
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/stop_policy/stop_policy.dart';
import '../../repositories/stop_policy_repository.dart';

class UpdateStopPolicyUseCase
    extends UseCase<StopPolicy, UpdateParams<String, StopPolicyPatch>> {
  UpdateStopPolicyUseCase(this._repository);

  final StopPolicyRepository _repository;

  @override
  Future<StopPolicy> execute(
    UpdateParams<String, StopPolicyPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
