// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
import '../../domain/entities/agent_tool/agent_tool.dart';
import '../../domain/entities/enums/index.dart';
import 'execution_mode_mock_data.dart';
import 'risk_tier_mock_data.dart';
import 'tool_source_mock_data.dart';

/// Mock data for AgentTool
class AgentToolMockData {
  static final List<AgentTool> agentTools = [
    AgentTool(
      id: 'id 1',
      name: 'name 1',
      description: 'description 1',
      inputSchema: {
        'key1 2': 'value1 1',
        'key2 3': 'value2 2',
        'key3 4': 'value3 3',
      },
      riskTier: RiskTier.values[1 % RiskTier.values.length],
      executionMode: ExecutionMode.values[1 % ExecutionMode.values.length],
      source: ToolSource.values[1 % ToolSource.values.length],
      transportBinding: 'transportBinding 1',
    ),
    AgentTool(
      id: 'id 2',
      name: 'name 2',
      description: 'description 2',
      inputSchema: {
        'key1 3': 'value1 2',
        'key2 4': 'value2 3',
        'key3 5': 'value3 4',
      },
      riskTier: RiskTier.values[2 % RiskTier.values.length],
      executionMode: ExecutionMode.values[2 % ExecutionMode.values.length],
      source: ToolSource.values[2 % ToolSource.values.length],
      transportBinding: 'transportBinding 2',
    ),
    AgentTool(
      id: 'id 3',
      name: 'name 3',
      description: 'description 3',
      inputSchema: {
        'key1 4': 'value1 3',
        'key2 5': 'value2 4',
        'key3 6': 'value3 5',
      },
      riskTier: RiskTier.values[3 % RiskTier.values.length],
      executionMode: ExecutionMode.values[3 % ExecutionMode.values.length],
      source: ToolSource.values[3 % ToolSource.values.length],
      transportBinding: null,
    ),
  ];

  static AgentTool get sampleAgentTool => agentTools.first;

  static List<AgentTool> get sampleList => agentTools;

  static List<AgentTool> get emptyList => <AgentTool>[];

  static List<AgentTool> get largeAgentToolList =>
      List.generate(100, (index) => _createAgentTool(index + 1000));

  static AgentTool _createAgentTool(int seed) {
    return AgentTool(
      id: 'id $seed',
      name: 'name $seed',
      description: 'description $seed',
      inputSchema: {
        'key ' + seed.toString(): 'value $seed',
        'key2 ' + seed.toString(): 'value2 $seed',
      },
      riskTier: RiskTier.values[seed % RiskTier.values.length],
      executionMode: ExecutionMode.values[seed % ExecutionMode.values.length],
      source: ToolSource.values[seed % ToolSource.values.length],
      transportBinding: seed % 3 == 0 ? null : 'transportBinding $seed',
    );
  }
}

// END GENERATED
