// GENERATED - DO NOT EDIT
// Generated by zfa for: ApprovalRequest
import '../../domain/entities/approval_request/approval_request.dart';

/// Mock data for ApprovalRequest
class ApprovalRequestMockData {
  static final List<ApprovalRequest> approvalRequests = [
    ApprovalRequest(
      toolName: 'toolName 1',
      arguments: {
        'key1 2': 'value1 1',
        'key2 3': 'value2 2',
        'key3 4': 'value3 3',
      },
      requestedAt: DateTime.now().subtract(const Duration(days: 30)),
      timeoutMs: 1,
      id: 'id 1',
    ),
    ApprovalRequest(
      toolName: 'toolName 2',
      arguments: {
        'key1 3': 'value1 2',
        'key2 4': 'value2 3',
        'key3 5': 'value3 4',
      },
      requestedAt: DateTime.now().subtract(const Duration(days: 60)),
      timeoutMs: 2,
      id: 'id 2',
    ),
    ApprovalRequest(
      toolName: 'toolName 3',
      arguments: {
        'key1 4': 'value1 3',
        'key2 5': 'value2 4',
        'key3 6': 'value3 5',
      },
      requestedAt: DateTime.now().subtract(const Duration(days: 90)),
      timeoutMs: 3,
      id: 'id 3',
    ),
  ];

  static ApprovalRequest get sampleApprovalRequest => approvalRequests.first;

  static List<ApprovalRequest> get sampleList => approvalRequests;

  static List<ApprovalRequest> get emptyList => <ApprovalRequest>[];

  static List<ApprovalRequest> get largeApprovalRequestList =>
      List.generate(100, (index) => _createApprovalRequest(index + 1000));

  static ApprovalRequest _createApprovalRequest(int seed) {
    return ApprovalRequest(
      toolName: 'toolName $seed',
      arguments: {
        'key ' + seed.toString(): 'value $seed',
        'key2 ' + seed.toString(): 'value2 $seed',
      },
      requestedAt: DateTime.now().subtract(Duration(days: seed * 30)),
      timeoutMs: seed * 10,
      id: 'id $seed',
    );
  }
}

// END GENERATED
