// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
import '../../domain/entities/artifact_ref/artifact_ref.dart';

/// Mock data for ArtifactRef
class ArtifactRefMockData {
  static final List<ArtifactRef> artifactRefs = [
    ArtifactRef(
      id: 'id 1',
      mimeType: 'mimeType 1',
      sizeBytes: 1,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    ArtifactRef(
      id: 'id 2',
      mimeType: 'mimeType 2',
      sizeBytes: 2,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    ArtifactRef(
      id: 'id 3',
      mimeType: 'mimeType 3',
      sizeBytes: 3,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
  ];

  static ArtifactRef get sampleArtifactRef => artifactRefs.first;

  static List<ArtifactRef> get sampleList => artifactRefs;

  static List<ArtifactRef> get emptyList => <ArtifactRef>[];

  static List<ArtifactRef> get largeArtifactRefList =>
      List.generate(100, (index) => _createArtifactRef(index + 1000));

  static ArtifactRef _createArtifactRef(int seed) {
    return ArtifactRef(
      id: 'id $seed',
      mimeType: 'mimeType $seed',
      sizeBytes: seed * 10,
      createdAt: DateTime.now().subtract(Duration(days: seed * 30)),
    );
  }
}

// END GENERATED
