// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
import '../../domain/entities/artifact_ref/artifact_ref.dart';

/// Mock data for ArtifactRef
class ArtifactRefMockData {
  static final List<ArtifactRef> artifactRefs = [
    ArtifactRef(kind: 'kind 1', id: 'id 1', uri: 'uri 1'),
    ArtifactRef(kind: 'kind 2', id: 'id 2', uri: 'uri 2'),
    ArtifactRef(kind: 'kind 3', id: 'id 3', uri: null),
  ];

  static ArtifactRef get sampleArtifactRef => artifactRefs.first;

  static List<ArtifactRef> get sampleList => artifactRefs;

  static List<ArtifactRef> get emptyList => <ArtifactRef>[];

  static List<ArtifactRef> get largeArtifactRefList =>
      List.generate(100, (index) => _createArtifactRef(index + 1000));

  static ArtifactRef _createArtifactRef(int seed) {
    return ArtifactRef(
      kind: 'kind $seed',
      id: 'id $seed',
      uri: seed % 3 == 0 ? null : 'uri $seed',
    );
  }
}

// END GENERATED
