// GENERATED - DO NOT EDIT
// Generated by zfa for: Artifact
import '../../domain/entities/artifact/artifact.dart';

/// Mock data for Artifact
class ArtifactMockData {
  static final List<Artifact> artifacts = [
    Artifact(refId: 'refId 1', data: [2, 3, 4]),
    Artifact(refId: 'refId 2', data: [3, 4, 5]),
    Artifact(refId: 'refId 3', data: [4, 5, 6]),
  ];

  static Artifact get sampleArtifact => artifacts.first;

  static List<Artifact> get sampleList => artifacts;

  static List<Artifact> get emptyList => <Artifact>[];

  static List<Artifact> get largeArtifactList =>
      List.generate(100, (index) => _createArtifact(index + 1000));

  static Artifact _createArtifact(int seed) {
    return Artifact(refId: 'refId $seed', data: [seed, seed + 1]);
  }
}

// END GENERATED
