// GENERATED - DO NOT EDIT
// Generated by zfa for: BranchSummaryEntry
import '../../domain/entities/branch_summary_entry/branch_summary_entry.dart';

/// Mock data for BranchSummaryEntry
class BranchSummaryEntryMockData {
  static final List<BranchSummaryEntry> branchSummaryEntrys = [
    BranchSummaryEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      summary: 'summary 1',
    ),
    BranchSummaryEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      summary: 'summary 2',
    ),
    BranchSummaryEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      summary: 'summary 3',
    ),
  ];

  static BranchSummaryEntry get sampleBranchSummaryEntry =>
      branchSummaryEntrys.first;

  static List<BranchSummaryEntry> get sampleList => branchSummaryEntrys;

  static List<BranchSummaryEntry> get emptyList => <BranchSummaryEntry>[];

  static List<BranchSummaryEntry> get largeBranchSummaryEntryList =>
      List.generate(100, (index) => _createBranchSummaryEntry(index + 1000));

  static BranchSummaryEntry _createBranchSummaryEntry(int seed) {
    return BranchSummaryEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      summary: 'summary $seed',
    );
  }
}

// END GENERATED
