// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionEntry
import '../../domain/entities/compaction_entry/compaction_entry.dart';

/// Mock data for CompactionEntry
class CompactionEntryMockData {
  static final List<CompactionEntry> compactionEntrys = [
    CompactionEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      firstKeptEntryId: 'firstKeptEntryId 1',
      tokensBefore: 1,
      tokensAfter: 1,
    ),
    CompactionEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      firstKeptEntryId: 'firstKeptEntryId 2',
      tokensBefore: 2,
      tokensAfter: 2,
    ),
    CompactionEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      firstKeptEntryId: 'firstKeptEntryId 3',
      tokensBefore: 3,
      tokensAfter: 3,
    ),
  ];

  static CompactionEntry get sampleCompactionEntry => compactionEntrys.first;

  static List<CompactionEntry> get sampleList => compactionEntrys;

  static List<CompactionEntry> get emptyList => <CompactionEntry>[];

  static List<CompactionEntry> get largeCompactionEntryList =>
      List.generate(100, (index) => _createCompactionEntry(index + 1000));

  static CompactionEntry _createCompactionEntry(int seed) {
    return CompactionEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      firstKeptEntryId: 'firstKeptEntryId $seed',
      tokensBefore: seed * 10,
      tokensAfter: seed * 10,
    );
  }
}

// END GENERATED
