// GENERATED - DO NOT EDIT
// ignore_for_file: prefer_interpolation_to_compose_strings
// Generated by zfa for: CompactionSummary
import '../../domain/entities/compaction_summary/compaction_summary.dart';

/// Mock data for CompactionSummary
class CompactionSummaryMockData {
  static final List<CompactionSummary> compactionSummarys = [
    CompactionSummary(
      decisions: ['item 2', 'item 3', 'item 4'],
      toolNames: ['item 2', 'item 3', 'item 4'],
      keyResults: ['item 2', 'item 3', 'item 4'],
      planState: 'planState 1',
    ),
    CompactionSummary(
      decisions: ['item 3', 'item 4', 'item 5'],
      toolNames: ['item 3', 'item 4', 'item 5'],
      keyResults: ['item 3', 'item 4', 'item 5'],
      planState: 'planState 2',
    ),
    CompactionSummary(
      decisions: ['item 4', 'item 5', 'item 6'],
      toolNames: ['item 4', 'item 5', 'item 6'],
      keyResults: ['item 4', 'item 5', 'item 6'],
      planState: null,
    ),
  ];

  static CompactionSummary get sampleCompactionSummary =>
      compactionSummarys.first;

  static List<CompactionSummary> get sampleList => compactionSummarys;

  static List<CompactionSummary> get emptyList => <CompactionSummary>[];

  static List<CompactionSummary> get largeCompactionSummaryList =>
      List.generate(100, (index) => _createCompactionSummary(index + 1000));

  static CompactionSummary _createCompactionSummary(int seed) {
    return CompactionSummary(
      decisions: ['item ' + seed.toString(), 'item ' + seed.toString()],
      toolNames: ['item ' + seed.toString(), 'item ' + seed.toString()],
      keyResults: ['item ' + seed.toString(), 'item ' + seed.toString()],
      planState: seed % 3 == 0 ? null : 'planState $seed',
    );
  }
}

// END GENERATED
