// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomEntry
import '../../domain/entities/custom_entry/custom_entry.dart';

/// Mock data for CustomEntry
class CustomEntryMockData {
  static final List<CustomEntry> customEntrys = [
    CustomEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      customType: 'customType 1',
      payload: 'payload 1',
    ),
    CustomEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      customType: 'customType 2',
      payload: 'payload 2',
    ),
    CustomEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      customType: 'customType 3',
      payload: 'payload 3',
    ),
  ];

  static CustomEntry get sampleCustomEntry => customEntrys.first;

  static List<CustomEntry> get sampleList => customEntrys;

  static List<CustomEntry> get emptyList => <CustomEntry>[];

  static List<CustomEntry> get largeCustomEntryList =>
      List.generate(100, (index) => _createCustomEntry(index + 1000));

  static CustomEntry _createCustomEntry(int seed) {
    return CustomEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      customType: 'customType $seed',
      payload: 'payload $seed',
    );
  }
}

// END GENERATED
