// GENERATED - DO NOT EDIT
// Generated by zfa for: ExecutionMode
import '../../domain/entities/enums/index.dart';

/// Mock data for ExecutionMode
class ExecutionModeMockData {
  static final List<ExecutionMode> executionModes = [
    ExecutionMode.values[0],
    ExecutionMode.values[1],
    ExecutionMode.values[0],
  ];

  static ExecutionMode get sampleExecutionMode => executionModes.first;

  static List<ExecutionMode> get sampleList => executionModes;

  static List<ExecutionMode> get emptyList => <ExecutionMode>[];

  static List<ExecutionMode> get largeExecutionModeList =>
      List.generate(100, (index) => _createExecutionMode(index + 1000));

  static ExecutionMode _createExecutionMode(int seed) {
    return ExecutionMode.values[seed % ExecutionMode.values.length];
  }
}

// END GENERATED
