// GENERATED - DO NOT EDIT
// Generated by zfa for: LabelEntry
import '../../domain/entities/label_entry/label_entry.dart';

/// Mock data for LabelEntry
class LabelEntryMockData {
  static final List<LabelEntry> labelEntrys = [
    LabelEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      label: 'label 1',
    ),
    LabelEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      label: 'label 2',
    ),
    LabelEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      label: 'label 3',
    ),
  ];

  static LabelEntry get sampleLabelEntry => labelEntrys.first;

  static List<LabelEntry> get sampleList => labelEntrys;

  static List<LabelEntry> get emptyList => <LabelEntry>[];

  static List<LabelEntry> get largeLabelEntryList =>
      List.generate(100, (index) => _createLabelEntry(index + 1000));

  static LabelEntry _createLabelEntry(int seed) {
    return LabelEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      label: 'label $seed',
    );
  }
}

// END GENERATED
