// GENERATED - DO NOT EDIT
// Generated by zfa for: ModelChangeEntry
import '../../domain/entities/model_change_entry/model_change_entry.dart';

/// Mock data for ModelChangeEntry
class ModelChangeEntryMockData {
  static final List<ModelChangeEntry> modelChangeEntrys = [
    ModelChangeEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      modelId: 'modelId 1',
      provider: 'provider 1',
    ),
    ModelChangeEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      modelId: 'modelId 2',
      provider: 'provider 2',
    ),
    ModelChangeEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      modelId: 'modelId 3',
      provider: 'provider 3',
    ),
  ];

  static ModelChangeEntry get sampleModelChangeEntry => modelChangeEntrys.first;

  static List<ModelChangeEntry> get sampleList => modelChangeEntrys;

  static List<ModelChangeEntry> get emptyList => <ModelChangeEntry>[];

  static List<ModelChangeEntry> get largeModelChangeEntryList =>
      List.generate(100, (index) => _createModelChangeEntry(index + 1000));

  static ModelChangeEntry _createModelChangeEntry(int seed) {
    return ModelChangeEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      modelId: 'modelId $seed',
      provider: 'provider $seed',
    );
  }
}

// END GENERATED
