// GENERATED - DO NOT EDIT
// Generated by zfa for: Model
import '../../domain/entities/model/model.dart';

/// Mock data for Model
class ModelMockData {
  static final List<Model> models = [
    Model(provider: 'provider 1', modelId: 'modelId 1', contextWindow: 1),
    Model(provider: 'provider 2', modelId: 'modelId 2', contextWindow: 2),
    Model(provider: 'provider 3', modelId: 'modelId 3', contextWindow: 3),
  ];

  static Model get sampleModel => models.first;

  static List<Model> get sampleList => models;

  static List<Model> get emptyList => <Model>[];

  static List<Model> get largeModelList =>
      List.generate(100, (index) => _createModel(index + 1000));

  static Model _createModel(int seed) {
    return Model(
      provider: 'provider $seed',
      modelId: 'modelId $seed',
      contextWindow: seed * 10,
    );
  }
}

// END GENERATED
