// GENERATED - DO NOT EDIT
// Generated by zfa for: RepetitionTracker
import '../../domain/entities/repetition_tracker/repetition_tracker.dart';

/// Mock data for RepetitionTracker
class RepetitionTrackerMockData {
  static final List<RepetitionTracker> repetitionTrackers = [
    RepetitionTracker(
      callSignatures: {'key1 2': 1, 'key2 3': 2, 'key3 4': 3},
      recentCalls: ['item 2', 'item 3', 'item 4'],
    ),
    RepetitionTracker(
      callSignatures: {'key1 3': 2, 'key2 4': 3, 'key3 5': 4},
      recentCalls: ['item 3', 'item 4', 'item 5'],
    ),
    RepetitionTracker(
      callSignatures: {'key1 4': 3, 'key2 5': 4, 'key3 6': 5},
      recentCalls: ['item 4', 'item 5', 'item 6'],
    ),
  ];

  static RepetitionTracker get sampleRepetitionTracker =>
      repetitionTrackers.first;

  static List<RepetitionTracker> get sampleList => repetitionTrackers;

  static List<RepetitionTracker> get emptyList => <RepetitionTracker>[];

  static List<RepetitionTracker> get largeRepetitionTrackerList =>
      List.generate(100, (index) => _createRepetitionTracker(index + 1000));

  static RepetitionTracker _createRepetitionTracker(int seed) {
    return RepetitionTracker(
      callSignatures: {
        'key ' + seed.toString(): seed * 10,
        'key2 ' + seed.toString(): seed * 10,
      },
      recentCalls: ['item ' + seed.toString(), 'item ' + seed.toString()],
    );
  }
}

// END GENERATED
