// GENERATED - DO NOT EDIT
// Generated by zfa for: RiskTier
import '../../domain/entities/enums/index.dart';

/// Mock data for RiskTier
class RiskTierMockData {
  static final List<RiskTier> riskTiers = [
    RiskTier.values[0],
    RiskTier.values[1],
    RiskTier.values[0],
  ];

  static RiskTier get sampleRiskTier => riskTiers.first;

  static List<RiskTier> get sampleList => riskTiers;

  static List<RiskTier> get emptyList => <RiskTier>[];

  static List<RiskTier> get largeRiskTierList =>
      List.generate(100, (index) => _createRiskTier(index + 1000));

  static RiskTier _createRiskTier(int seed) {
    return RiskTier.values[seed % RiskTier.values.length];
  }
}

// END GENERATED
