// GENERATED - DO NOT EDIT
// Generated by zfa for: StopPolicy
import '../../domain/entities/stop_policy/stop_policy.dart';

/// Mock data for StopPolicy
class StopPolicyMockData {
  static final List<StopPolicy> stopPolicys = [
    StopPolicy(
      maxTurns: 1,
      wallClockTimeoutMs: 1,
      repetitionThreshold: 1,
      enabled: true,
    ),
    StopPolicy(
      maxTurns: 2,
      wallClockTimeoutMs: 2,
      repetitionThreshold: 2,
      enabled: false,
    ),
    StopPolicy(
      maxTurns: 3,
      wallClockTimeoutMs: 3,
      repetitionThreshold: 3,
      enabled: true,
    ),
  ];

  static StopPolicy get sampleStopPolicy => stopPolicys.first;

  static List<StopPolicy> get sampleList => stopPolicys;

  static List<StopPolicy> get emptyList => <StopPolicy>[];

  static List<StopPolicy> get largeStopPolicyList =>
      List.generate(100, (index) => _createStopPolicy(index + 1000));

  static StopPolicy _createStopPolicy(int seed) {
    return StopPolicy(
      maxTurns: seed * 10,
      wallClockTimeoutMs: seed * 10,
      repetitionThreshold: seed * 10,
      enabled: seed % 2 == 1,
    );
  }
}

// END GENERATED
