// GENERATED - DO NOT EDIT
// Generated by zfa for: ThinkingLevelChangeEntry
import '../../domain/entities/thinking_level_change_entry/thinking_level_change_entry.dart';

/// Mock data for ThinkingLevelChangeEntry
class ThinkingLevelChangeEntryMockData {
  static final List<ThinkingLevelChangeEntry> thinkingLevelChangeEntrys = [
    ThinkingLevelChangeEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      thinkingLevel: 'thinkingLevel 1',
    ),
    ThinkingLevelChangeEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      thinkingLevel: 'thinkingLevel 2',
    ),
    ThinkingLevelChangeEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      thinkingLevel: 'thinkingLevel 3',
    ),
  ];

  static ThinkingLevelChangeEntry get sampleThinkingLevelChangeEntry =>
      thinkingLevelChangeEntrys.first;

  static List<ThinkingLevelChangeEntry> get sampleList =>
      thinkingLevelChangeEntrys;

  static List<ThinkingLevelChangeEntry> get emptyList =>
      <ThinkingLevelChangeEntry>[];

  static List<ThinkingLevelChangeEntry> get largeThinkingLevelChangeEntryList =>
      List.generate(
        100,
        (index) => _createThinkingLevelChangeEntry(index + 1000),
      );

  static ThinkingLevelChangeEntry _createThinkingLevelChangeEntry(int seed) {
    return ThinkingLevelChangeEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      thinkingLevel: 'thinkingLevel $seed',
    );
  }
}

// END GENERATED
