// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolCallSignature
import '../../domain/entities/tool_call_signature/tool_call_signature.dart';

/// Mock data for ToolCallSignature
class ToolCallSignatureMockData {
  static final List<ToolCallSignature> toolCallSignatures = [
    ToolCallSignature(
      toolName: 'toolName 1',
      normalizedArgs: 'normalizedArgs 1',
    ),
    ToolCallSignature(
      toolName: 'toolName 2',
      normalizedArgs: 'normalizedArgs 2',
    ),
    ToolCallSignature(
      toolName: 'toolName 3',
      normalizedArgs: 'normalizedArgs 3',
    ),
  ];

  static ToolCallSignature get sampleToolCallSignature =>
      toolCallSignatures.first;

  static List<ToolCallSignature> get sampleList => toolCallSignatures;

  static List<ToolCallSignature> get emptyList => <ToolCallSignature>[];

  static List<ToolCallSignature> get largeToolCallSignatureList =>
      List.generate(100, (index) => _createToolCallSignature(index + 1000));

  static ToolCallSignature _createToolCallSignature(int seed) {
    return ToolCallSignature(
      toolName: 'toolName $seed',
      normalizedArgs: 'normalizedArgs $seed',
    );
  }
}

// END GENERATED
