// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolSource
import '../../domain/entities/enums/index.dart';

/// Mock data for ToolSource
class ToolSourceMockData {
  static final List<ToolSource> toolSources = [
    ToolSource.values[0],
    ToolSource.values[1],
    ToolSource.values[0],
  ];

  static ToolSource get sampleToolSource => toolSources.first;

  static List<ToolSource> get sampleList => toolSources;

  static List<ToolSource> get emptyList => <ToolSource>[];

  static List<ToolSource> get largeToolSourceList =>
      List.generate(100, (index) => _createToolSource(index + 1000));

  static ToolSource _createToolSource(int seed) {
    return ToolSource.values[seed % ToolSource.values.length];
  }
}

// END GENERATED
