// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
import '../../domain/entities/tool_invocation_record/tool_invocation_record.dart';

/// Mock data for ToolInvocationRecord
class ToolInvocationRecordMockData {
  static final List<ToolInvocationRecord> toolInvocationRecords = [
    ToolInvocationRecord(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      toolCallId: 'toolCallId 1',
      toolName: 'toolName 1',
      resultEntryId: 'resultEntryId 1',
      isError: true,
      durationMs: 1,
    ),
    ToolInvocationRecord(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      toolCallId: 'toolCallId 2',
      toolName: 'toolName 2',
      resultEntryId: 'resultEntryId 2',
      isError: false,
      durationMs: 2,
    ),
    ToolInvocationRecord(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      toolCallId: 'toolCallId 3',
      toolName: 'toolName 3',
      resultEntryId: null,
      isError: true,
      durationMs: 3,
    ),
  ];

  static ToolInvocationRecord get sampleToolInvocationRecord =>
      toolInvocationRecords.first;

  static List<ToolInvocationRecord> get sampleList => toolInvocationRecords;

  static List<ToolInvocationRecord> get emptyList => <ToolInvocationRecord>[];

  static List<ToolInvocationRecord> get largeToolInvocationRecordList =>
      List.generate(100, (index) => _createToolInvocationRecord(index + 1000));

  static ToolInvocationRecord _createToolInvocationRecord(int seed) {
    return ToolInvocationRecord(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      toolCallId: 'toolCallId $seed',
      toolName: 'toolName $seed',
      resultEntryId: seed % 3 == 0 ? null : 'resultEntryId $seed',
      isError: seed % 2 == 1,
      durationMs: seed * 10,
    );
  }
}

// END GENERATED
