// GENERATED - DO NOT EDIT
// ignore_for_file: prefer_interpolation_to_compose_strings
// Generated by zfa for: TurnRecord
import '../../domain/entities/turn_record/turn_record.dart';

/// Mock data for TurnRecord
class TurnRecordMockData {
  static final List<TurnRecord> turnRecords = [
    TurnRecord(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      turnNumber: 1,
      messageEntryIds: ['item 2', 'item 3', 'item 4'],
      toolInvocationEntryIds: ['item 2', 'item 3', 'item 4'],
      stopReason: 'stopReason 1',
      startedAt: DateTime.now().subtract(const Duration(days: 30)),
      endedAt: DateTime.now().subtract(const Duration(days: 30)),
      durationMs: 1,
    ),
    TurnRecord(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      turnNumber: 2,
      messageEntryIds: ['item 3', 'item 4', 'item 5'],
      toolInvocationEntryIds: ['item 3', 'item 4', 'item 5'],
      stopReason: 'stopReason 2',
      startedAt: DateTime.now().subtract(const Duration(days: 60)),
      endedAt: DateTime.now().subtract(const Duration(days: 60)),
      durationMs: 2,
    ),
    TurnRecord(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      turnNumber: 3,
      messageEntryIds: ['item 4', 'item 5', 'item 6'],
      toolInvocationEntryIds: ['item 4', 'item 5', 'item 6'],
      stopReason: 'stopReason 3',
      startedAt: DateTime.now().subtract(const Duration(days: 90)),
      endedAt: DateTime.now().subtract(const Duration(days: 90)),
      durationMs: 3,
    ),
  ];

  static TurnRecord get sampleTurnRecord => turnRecords.first;

  static List<TurnRecord> get sampleList => turnRecords;

  static List<TurnRecord> get emptyList => <TurnRecord>[];

  static List<TurnRecord> get largeTurnRecordList =>
      List.generate(100, (index) => _createTurnRecord(index + 1000));

  static TurnRecord _createTurnRecord(int seed) {
    return TurnRecord(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      turnNumber: seed * 10,
      messageEntryIds: ['item ' + seed.toString(), 'item ' + seed.toString()],
      toolInvocationEntryIds: [
        'item ' + seed.toString(),
        'item ' + seed.toString(),
      ],
      stopReason: 'stopReason $seed',
      startedAt: DateTime.now().subtract(Duration(days: seed * 30)),
      endedAt: DateTime.now().subtract(Duration(days: seed * 30)),
      durationMs: seed * 10,
    );
  }
}

// END GENERATED
