// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
import '../../domain/entities/usage_ledger_entry/usage_ledger_entry.dart';

/// Mock data for UsageLedgerEntry
class UsageLedgerEntryMockData {
  static final List<UsageLedgerEntry> usageLedgerEntrys = [
    UsageLedgerEntry(
      id: 'id 1',
      parentId: 'parentId 1',
      timestamp: DateTime.now().subtract(const Duration(days: 30)),
      callId: 'callId 1',
      turnNumber: 1,
      inputTokens: 1,
      outputTokens: 1,
      cacheReadTokens: 1,
      cacheWriteTokens: 1,
    ),
    UsageLedgerEntry(
      id: 'id 2',
      parentId: 'parentId 2',
      timestamp: DateTime.now().subtract(const Duration(days: 60)),
      callId: 'callId 2',
      turnNumber: 2,
      inputTokens: 2,
      outputTokens: 2,
      cacheReadTokens: 2,
      cacheWriteTokens: 2,
    ),
    UsageLedgerEntry(
      id: 'id 3',
      parentId: null,
      timestamp: DateTime.now().subtract(const Duration(days: 90)),
      callId: 'callId 3',
      turnNumber: 3,
      inputTokens: 3,
      outputTokens: 3,
      cacheReadTokens: 3,
      cacheWriteTokens: 3,
    ),
  ];

  static UsageLedgerEntry get sampleUsageLedgerEntry => usageLedgerEntrys.first;

  static List<UsageLedgerEntry> get sampleList => usageLedgerEntrys;

  static List<UsageLedgerEntry> get emptyList => <UsageLedgerEntry>[];

  static List<UsageLedgerEntry> get largeUsageLedgerEntryList =>
      List.generate(100, (index) => _createUsageLedgerEntry(index + 1000));

  static UsageLedgerEntry _createUsageLedgerEntry(int seed) {
    return UsageLedgerEntry(
      id: 'id $seed',
      parentId: seed % 3 == 0 ? null : 'parentId $seed',
      timestamp: DateTime.now().subtract(Duration(days: seed * 30)),
      callId: 'callId $seed',
      turnNumber: seed * 10,
      inputTokens: seed * 10,
      outputTokens: seed * 10,
      cacheReadTokens: seed * 10,
      cacheWriteTokens: seed * 10,
    );
  }
}

// END GENERATED
