// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
// zfa make AgentTool --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/agent_tool/agent_tool.dart';

abstract class AgentToolRepository {
  Future<AgentTool> get(QueryParams<AgentTool> params);
  Future<AgentTool> update(UpdateParams<String, AgentToolPatch> params);
  Future<AgentTool> toggle(
    ToggleParams<String, Field<AgentTool, dynamic>> params,
  );
}

// END GENERATED
