// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentSpec
// zfa make AgentSpec --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/agent_spec/agent_spec.dart';

abstract class AgentSpecRepository {
  Future<AgentSpec> get(QueryParams<AgentSpec> params);
  Future<AgentSpec> update(UpdateParams<String, AgentSpecPatch> params);
}

// END GENERATED
