// GENERATED - DO NOT EDIT
// Generated by zfa for: ApprovalRequest
// zfa make ApprovalRequest --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/approval_request/approval_request.dart';

abstract class ApprovalRequestRepository {
  Future<ApprovalRequest> get(QueryParams<ApprovalRequest> params);
  Future<ApprovalRequest> update(
    UpdateParams<String, ApprovalRequestPatch> params,
  );
  Future<ApprovalRequest> toggle(
    ToggleParams<String, Field<ApprovalRequest, dynamic>> params,
  );
}

// END GENERATED
