// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactServiceConfig
// zfa make ArtifactServiceConfig --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/artifact_service_config/artifact_service_config.dart';

abstract class ArtifactServiceConfigRepository {
  Future<ArtifactServiceConfig> get(QueryParams<ArtifactServiceConfig> params);
  Future<ArtifactServiceConfig> update(
    UpdateParams<String, ArtifactServiceConfigPatch> params,
  );
}

// END GENERATED
