// GENERATED - DO NOT EDIT
// Generated by zfa for: Artifact
// zfa make Artifact --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/artifact/artifact.dart';

abstract class ArtifactRepository {
  Future<Artifact> get(QueryParams<Artifact> params);
  Future<Artifact> update(UpdateParams<String, ArtifactPatch> params);
  Future<Artifact> toggle(
    ToggleParams<String, Field<Artifact, dynamic>> params,
  );
}

// END GENERATED
