// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
// zfa make ArtifactRef --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/artifact_ref/artifact_ref.dart';

abstract class ArtifactRefRepository {
  Future<ArtifactRef> get(QueryParams<ArtifactRef> params);
  Future<ArtifactRef> update(UpdateParams<String, ArtifactRefPatch> params);
  Future<ArtifactRef> toggle(
    ToggleParams<String, Field<ArtifactRef, dynamic>> params,
  );
}

// END GENERATED
