// GENERATED - DO NOT EDIT
// Generated by zfa for: BranchSummaryEntry
// zfa make BranchSummaryEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/branch_summary_entry/branch_summary_entry.dart';

abstract class BranchSummaryEntryRepository {
  Future<BranchSummaryEntry> get(QueryParams<BranchSummaryEntry> params);
  Future<BranchSummaryEntry> update(
    UpdateParams<String, BranchSummaryEntryPatch> params,
  );
}

// END GENERATED
