// GENERATED - DO NOT EDIT
// Generated by zfa for: ClientHealth
// zfa make ClientHealth --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/client_health/client_health.dart';

abstract class ClientHealthRepository {
  Future<ClientHealth> get(QueryParams<ClientHealth> params);
  Future<ClientHealth> update(UpdateParams<String, ClientHealthPatch> params);
}

// END GENERATED
