// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionEntry
// zfa make CompactionEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/compaction_entry/compaction_entry.dart';

abstract class CompactionEntryRepository {
  Future<CompactionEntry> get(QueryParams<CompactionEntry> params);
  Future<CompactionEntry> update(
    UpdateParams<String, CompactionEntryPatch> params,
  );
}

// END GENERATED
