// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionSummary
// zfa make CompactionSummary --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/compaction_summary/compaction_summary.dart';

abstract class CompactionSummaryRepository {
  Future<CompactionSummary> get(QueryParams<CompactionSummary> params);
  Future<CompactionSummary> update(
    UpdateParams<String, CompactionSummaryPatch> params,
  );
}

// END GENERATED
