// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomEntry
// zfa make CustomEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/custom_entry/custom_entry.dart';

abstract class CustomEntryRepository {
  Future<CustomEntry> get(QueryParams<CustomEntry> params);
  Future<CustomEntry> update(UpdateParams<String, CustomEntryPatch> params);
}

// END GENERATED
