// GENERATED - DO NOT EDIT
// Generated by zfa for: DispatchTool
// zfa make DispatchTool --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/dispatch_tool/dispatch_tool.dart';

abstract class DispatchToolRepository {
  Future<DispatchTool> get(QueryParams<DispatchTool> params);
  Future<DispatchTool> update(UpdateParams<String, DispatchToolPatch> params);
}

// END GENERATED
