// GENERATED - DO NOT EDIT
// Generated by zfa for: EngineEvent
// zfa make EngineEvent --methods=get --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/engine_event/engine_event.dart';

abstract class EngineEventRepository {
  Future<EngineEvent> get(QueryParams<EngineEvent> params);
}

// END GENERATED
