// GENERATED - DO NOT EDIT
// Generated by zfa for: Enums
// zfa make Enums --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/enums/enums.dart';

abstract class EnumsRepository {
  Future<Enums> get(QueryParams<Enums> params);
  Future<Enums> update(UpdateParams<String, EnumsPatch> params);
}

// END GENERATED
