// GENERATED - DO NOT EDIT
// Generated by zfa for: FallbackChain
// zfa make FallbackChain --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/fallback_chain/fallback_chain.dart';

abstract class FallbackChainRepository {
  Future<FallbackChain> get(QueryParams<FallbackChain> params);
  Future<FallbackChain> update(UpdateParams<String, FallbackChainPatch> params);
}

// END GENERATED
