// GENERATED - DO NOT EDIT
// Generated by zfa for: GoldenMission
// zfa make GoldenMission --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/golden_mission/golden_mission.dart';

abstract class GoldenMissionRepository {
  Future<GoldenMission> get(QueryParams<GoldenMission> params);
  Future<GoldenMission> update(UpdateParams<String, GoldenMissionPatch> params);
}

// END GENERATED
