// GENERATED - DO NOT EDIT
// Generated by zfa for: LabelEntry
// zfa make LabelEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/label_entry/label_entry.dart';

abstract class LabelEntryRepository {
  Future<LabelEntry> get(QueryParams<LabelEntry> params);
  Future<LabelEntry> update(UpdateParams<String, LabelEntryPatch> params);
}

// END GENERATED
