// GENERATED - DO NOT EDIT
// Generated by zfa for: MissionConfig
// zfa make MissionConfig --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/mission_config/mission_config.dart';

abstract class MissionConfigRepository {
  Future<MissionConfig> get(QueryParams<MissionConfig> params);
  Future<MissionConfig> update(UpdateParams<String, MissionConfigPatch> params);
}

// END GENERATED
