// GENERATED - DO NOT EDIT
// Generated by zfa for: ModelChangeEntry
// zfa make ModelChangeEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/model_change_entry/model_change_entry.dart';

abstract class ModelChangeEntryRepository {
  Future<ModelChangeEntry> get(QueryParams<ModelChangeEntry> params);
  Future<ModelChangeEntry> update(
    UpdateParams<String, ModelChangeEntryPatch> params,
  );
}

// END GENERATED
