// GENERATED - DO NOT EDIT
// Generated by zfa for: RepetitionTracker
// zfa make RepetitionTracker --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/repetition_tracker/repetition_tracker.dart';

abstract class RepetitionTrackerRepository {
  Future<RepetitionTracker> get(QueryParams<RepetitionTracker> params);
  Future<RepetitionTracker> update(
    UpdateParams<String, RepetitionTrackerPatch> params,
  );
}

// END GENERATED
