// GENERATED - DO NOT EDIT
// Generated by zfa for: StopPolicy
// zfa make StopPolicy --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/stop_policy/stop_policy.dart';

abstract class StopPolicyRepository {
  Future<StopPolicy> get(QueryParams<StopPolicy> params);
  Future<StopPolicy> update(UpdateParams<String, StopPolicyPatch> params);
}

// END GENERATED
