// GENERATED - DO NOT EDIT
// Generated by zfa for: SubAgentType
// zfa make SubAgentType --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/sub_agent_type/sub_agent_type.dart';

abstract class SubAgentTypeRepository {
  Future<SubAgentType> get(QueryParams<SubAgentType> params);
  Future<SubAgentType> update(UpdateParams<String, SubAgentTypePatch> params);
}

// END GENERATED
