// GENERATED - DO NOT EDIT
// Generated by zfa for: Suite
// zfa make Suite --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/suite/suite.dart';

abstract class SuiteRepository {
  Future<Suite> get(QueryParams<Suite> params);
  Future<Suite> update(UpdateParams<String, SuitePatch> params);
}

// END GENERATED
