// GENERATED - DO NOT EDIT
// Generated by zfa for: ThinkingLevelChangeEntry
// zfa make ThinkingLevelChangeEntry --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/thinking_level_change_entry/thinking_level_change_entry.dart';

abstract class ThinkingLevelChangeEntryRepository {
  Future<ThinkingLevelChangeEntry> get(
    QueryParams<ThinkingLevelChangeEntry> params,
  );
  Future<ThinkingLevelChangeEntry> update(
    UpdateParams<String, ThinkingLevelChangeEntryPatch> params,
  );
}

// END GENERATED
