// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolCallSignature
// zfa make ToolCallSignature --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/tool_call_signature/tool_call_signature.dart';

abstract class ToolCallSignatureRepository {
  Future<ToolCallSignature> get(QueryParams<ToolCallSignature> params);
  Future<ToolCallSignature> update(
    UpdateParams<String, ToolCallSignaturePatch> params,
  );
}

// END GENERATED
