// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
// zfa make ToolInvocationRecord --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/tool_invocation_record/tool_invocation_record.dart';

abstract class ToolInvocationRecordRepository {
  Future<ToolInvocationRecord> get(QueryParams<ToolInvocationRecord> params);
  Future<List<ToolInvocationRecord>> getList(
    ListQueryParams<ToolInvocationRecord> params,
  );
  Future<ToolInvocationRecord> create(
    ToolInvocationRecord toolInvocationRecord,
  );
  Future<ToolInvocationRecord> update(
    UpdateParams<String, ToolInvocationRecordPatch> params,
  );
  Future<void> delete(DeleteParams<String> params);
}

// END GENERATED
