// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnContext
// zfa make TurnContext --methods=get,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/turn_context/turn_context.dart';

abstract class TurnContextRepository {
  Future<TurnContext> get(QueryParams<TurnContext> params);
  Future<TurnContext> update(UpdateParams<String, TurnContextPatch> params);
}

// END GENERATED
