// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnRecord
// zfa make TurnRecord --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/turn_record/turn_record.dart';

abstract class TurnRecordRepository {
  Future<TurnRecord> get(QueryParams<TurnRecord> params);
  Future<List<TurnRecord>> getList(ListQueryParams<TurnRecord> params);
  Future<TurnRecord> create(TurnRecord turnRecord);
  Future<TurnRecord> update(UpdateParams<String, TurnRecordPatch> params);
  Future<void> delete(DeleteParams<String> params);
}

// END GENERATED
