// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
// zfa make UsageLedgerEntry --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/usage_ledger_entry/usage_ledger_entry.dart';

abstract class UsageLedgerEntryRepository {
  Future<UsageLedgerEntry> get(QueryParams<UsageLedgerEntry> params);
  Future<List<UsageLedgerEntry>> getList(
    ListQueryParams<UsageLedgerEntry> params,
  );
  Future<UsageLedgerEntry> create(UsageLedgerEntry usageLedgerEntry);
  Future<UsageLedgerEntry> update(
    UpdateParams<String, UsageLedgerEntryPatch> params,
  );
  Future<void> delete(DeleteParams<String> params);
}

// END GENERATED
