// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_tool/agent_tool.dart';
import '../../repositories/agent_tool_repository.dart';

class GetAgentToolUseCase extends UseCase<AgentTool, QueryParams<AgentTool>> {
  GetAgentToolUseCase(this._repository);

  final AgentToolRepository _repository;

  @override
  Future<AgentTool> execute(
    QueryParams<AgentTool> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
