// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_tool/agent_tool.dart';
import '../../repositories/agent_tool_repository.dart';

class ToggleAgentToolUseCase
    extends
        UseCase<AgentTool, ToggleParams<String, Field<AgentTool, dynamic>>> {
  ToggleAgentToolUseCase(this._repository);

  final AgentToolRepository _repository;

  @override
  Future<AgentTool> execute(
    ToggleParams<String, Field<AgentTool, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
