// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_tool/agent_tool.dart';
import '../../repositories/agent_tool_repository.dart';

class UpdateAgentToolUseCase
    extends UseCase<AgentTool, UpdateParams<String, AgentToolPatch>> {
  UpdateAgentToolUseCase(this._repository);

  final AgentToolRepository _repository;

  @override
  Future<AgentTool> execute(
    UpdateParams<String, AgentToolPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
