// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:41.802971

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'branch_summary_entry.zorphy.dart';
part 'branch_summary_entry.g.dart';

/// BranchSummaryEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $BranchSummaryEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get summary;
}

