// Auto-generated by Zorphy
// Generated at: 2026-08-21T15:53:24.607052

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'future.zorphy.dart';
part 'future.g.dart';

/// Future entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Future {
  String get id;
  dynamic get value;
}
