// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:35:19.261425

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'client_health.zorphy.dart';
part 'client_health.g.dart';

/// ClientHealth entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $ClientHealth {

  String get id;
  String get state;
  int get consecutiveFailures;
  int get cooldownWindowMs;
  DateTime get lastFailureAt;
  bool get isHealthy;
}

