// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact_ref/artifact_ref.dart';
import '../../repositories/artifact_ref_repository.dart';

class GetArtifactRefUseCase
    extends UseCase<ArtifactRef, QueryParams<ArtifactRef>> {
  GetArtifactRefUseCase(this._repository);

  final ArtifactRefRepository _repository;

  @override
  Future<ArtifactRef> execute(
    QueryParams<ArtifactRef> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
