// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact_ref/artifact_ref.dart';
import '../../repositories/artifact_ref_repository.dart';

class UpdateArtifactRefUseCase
    extends UseCase<ArtifactRef, UpdateParams<String, ArtifactRefPatch>> {
  UpdateArtifactRefUseCase(this._repository);

  final ArtifactRefRepository _repository;

  @override
  Future<ArtifactRef> execute(
    UpdateParams<String, ArtifactRefPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
