// GENERATED - DO NOT EDIT
// Generated by zfa for: FallbackChain
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/fallback_chain/fallback_chain.dart';
import '../../repositories/fallback_chain_repository.dart';

class GetFallbackChainUseCase
    extends UseCase<FallbackChain, QueryParams<FallbackChain>> {
  GetFallbackChainUseCase(this._repository);

  final FallbackChainRepository _repository;

  @override
  Future<FallbackChain> execute(
    QueryParams<FallbackChain> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
