// GENERATED - DO NOT EDIT
// Generated by zfa for: FallbackChain
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/fallback_chain/fallback_chain.dart';
import '../../repositories/fallback_chain_repository.dart';

class UpdateFallbackChainUseCase
    extends UseCase<FallbackChain, UpdateParams<String, FallbackChainPatch>> {
  UpdateFallbackChainUseCase(this._repository);

  final FallbackChainRepository _repository;

  @override
  Future<FallbackChain> execute(
    UpdateParams<String, FallbackChainPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
