// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_invocation_record/tool_invocation_record.dart';
import '../../repositories/tool_invocation_record_repository.dart';

class CreateToolInvocationRecordUseCase
    extends UseCase<ToolInvocationRecord, ToolInvocationRecord> {
  CreateToolInvocationRecordUseCase(this._repository);

  final ToolInvocationRecordRepository _repository;

  @override
  Future<ToolInvocationRecord> execute(
    ToolInvocationRecord params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
