// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
import 'package:zuraffa/zuraffa.dart';

import '../../repositories/tool_invocation_record_repository.dart';

class DeleteToolInvocationRecordUseCase
    extends CompletableUseCase<DeleteParams<String>> {
  DeleteToolInvocationRecordUseCase(this._repository);

  final ToolInvocationRecordRepository _repository;

  @override
  Future<void> execute(
    DeleteParams<String> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.delete(params);
  }
}

// END GENERATED
