// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_invocation_record/tool_invocation_record.dart';
import '../../repositories/tool_invocation_record_repository.dart';

class GetToolInvocationRecordListUseCase
    extends
        UseCase<
          List<ToolInvocationRecord>,
          ListQueryParams<ToolInvocationRecord>
        > {
  GetToolInvocationRecordListUseCase(this._repository);

  final ToolInvocationRecordRepository _repository;

  @override
  Future<List<ToolInvocationRecord>> execute(
    ListQueryParams<ToolInvocationRecord> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList(params);
  }
}

// END GENERATED
