// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_invocation_record/tool_invocation_record.dart';
import '../../repositories/tool_invocation_record_repository.dart';

class GetToolInvocationRecordUseCase
    extends UseCase<ToolInvocationRecord, QueryParams<ToolInvocationRecord>> {
  GetToolInvocationRecordUseCase(this._repository);

  final ToolInvocationRecordRepository _repository;

  @override
  Future<ToolInvocationRecord> execute(
    QueryParams<ToolInvocationRecord> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
