// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolInvocationRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_invocation_record/tool_invocation_record.dart';
import '../../repositories/tool_invocation_record_repository.dart';

class UpdateToolInvocationRecordUseCase
    extends
        UseCase<
          ToolInvocationRecord,
          UpdateParams<String, ToolInvocationRecordPatch>
        > {
  UpdateToolInvocationRecordUseCase(this._repository);

  final ToolInvocationRecordRepository _repository;

  @override
  Future<ToolInvocationRecord> execute(
    UpdateParams<String, ToolInvocationRecordPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
