// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/usage_ledger_entry/usage_ledger_entry.dart';
import '../../repositories/usage_ledger_entry_repository.dart';

class CreateUsageLedgerEntryUseCase
    extends UseCase<UsageLedgerEntry, UsageLedgerEntry> {
  CreateUsageLedgerEntryUseCase(this._repository);

  final UsageLedgerEntryRepository _repository;

  @override
  Future<UsageLedgerEntry> execute(
    UsageLedgerEntry params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
