// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
import 'package:zuraffa/zuraffa.dart';

import '../../repositories/usage_ledger_entry_repository.dart';

class DeleteUsageLedgerEntryUseCase
    extends CompletableUseCase<DeleteParams<String>> {
  DeleteUsageLedgerEntryUseCase(this._repository);

  final UsageLedgerEntryRepository _repository;

  @override
  Future<void> execute(
    DeleteParams<String> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.delete(params);
  }
}

// END GENERATED
