// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/usage_ledger_entry/usage_ledger_entry.dart';
import '../../repositories/usage_ledger_entry_repository.dart';

class GetUsageLedgerEntryUseCase
    extends UseCase<UsageLedgerEntry, QueryParams<UsageLedgerEntry>> {
  GetUsageLedgerEntryUseCase(this._repository);

  final UsageLedgerEntryRepository _repository;

  @override
  Future<UsageLedgerEntry> execute(
    QueryParams<UsageLedgerEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
