// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/usage_ledger_entry/usage_ledger_entry.dart';
import '../../repositories/usage_ledger_entry_repository.dart';

class GetUsageLedgerEntryListUseCase
    extends UseCase<List<UsageLedgerEntry>, ListQueryParams<UsageLedgerEntry>> {
  GetUsageLedgerEntryListUseCase(this._repository);

  final UsageLedgerEntryRepository _repository;

  @override
  Future<List<UsageLedgerEntry>> execute(
    ListQueryParams<UsageLedgerEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList(params);
  }
}

// END GENERATED
