// GENERATED - DO NOT EDIT
// Generated by zfa for: UsageLedgerEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/usage_ledger_entry/usage_ledger_entry.dart';
import '../../repositories/usage_ledger_entry_repository.dart';

class UpdateUsageLedgerEntryUseCase
    extends
        UseCase<UsageLedgerEntry, UpdateParams<String, UsageLedgerEntryPatch>> {
  UpdateUsageLedgerEntryUseCase(this._repository);

  final UsageLedgerEntryRepository _repository;

  @override
  Future<UsageLedgerEntry> execute(
    UpdateParams<String, UsageLedgerEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
