// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:36.324723

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'usage_ledger_entry.zorphy.dart';
part 'usage_ledger_entry.g.dart';

/// UsageLedgerEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UsageLedgerEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get callId;
  int get turnNumber;
  int get inputTokens;
  int get outputTokens;
  int get cacheReadTokens;
  int get cacheWriteTokens;
}

