// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:50.985441

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'compaction_summary.zorphy.dart';
part 'compaction_summary.g.dart';

/// CompactionSummary entity
@Zorphy(kind: ZorphyKind.valueObject, generateJson: true, generateCompareTo: true)
abstract class $CompactionSummary {

  List<String> get decisions;
  List<String> get toolNames;
  List<String> get keyResults;
  String? get planState;
}

