// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:23:56.274018

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'tool_call_signature.zorphy.dart';
part 'tool_call_signature.g.dart';

/// ToolCallSignature entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $ToolCallSignature {

  String get id;
  String get toolName;
  String get normalizedArgs;
}

