// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionSummary
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/compaction_summary/compaction_summary.dart';
import '../../repositories/compaction_summary_repository.dart';

class GetCompactionSummaryUseCase
    extends UseCase<CompactionSummary, QueryParams<CompactionSummary>> {
  GetCompactionSummaryUseCase(this._repository);

  final CompactionSummaryRepository _repository;

  @override
  Future<CompactionSummary> execute(
    QueryParams<CompactionSummary> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
