// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionSummary
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/compaction_summary/compaction_summary.dart';
import '../../repositories/compaction_summary_repository.dart';

class UpdateCompactionSummaryUseCase
    extends
        UseCase<
          CompactionSummary,
          UpdateParams<String, CompactionSummaryPatch>
        > {
  UpdateCompactionSummaryUseCase(this._repository);

  final CompactionSummaryRepository _repository;

  @override
  Future<CompactionSummary> execute(
    UpdateParams<String, CompactionSummaryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
