// Auto-generated by Zorphy
// Generated at: 2026-08-27T16:45:31.454267

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'approval_request.zorphy.dart';
part 'approval_request.g.dart';

/// ApprovalRequest entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ApprovalRequest {

  String get id;
  String get toolName;
  Map<String, dynamic> get arguments;
  DateTime get requestedAt;
  int get timeoutMs;
}

