// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:38:16.683405

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'dispatch_tool.zorphy.dart';
part 'dispatch_tool.g.dart';

/// DispatchTool entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $DispatchTool {

  String get id;
  String get type;
  String get task;
  String get instanceId;
  String get lifecycle;
}

