// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:18:47.954978

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'engine_event.zorphy.dart';
part 'engine_event.g.dart';

/// EngineEvent entity
@Zorphy(generateJson: true, generateCompareTo: true, explicitSubTypes: [$MissionStarted, $MissionCompleted, $TurnStarted, $TurnCompleted, $ThinkingDelta, $TextDelta, $ToolCallStarted, $ToolCallCompleted, $ProviderError, $SteeringInjected])
abstract class $$EngineEvent {

  String get eventId;
  int get sequenceNumber;
  DateTime get timestamp;
  String get missionId;
}

@Zorphy(generateJson: true)
abstract class $MissionStarted implements $$EngineEvent {
  Map<String, dynamic> get config;
}

@Zorphy(generateJson: true)
abstract class $MissionCompleted implements $$EngineEvent {
  String get outcome;
  String? get errorMessage;
  int get totalTurns;
}

@Zorphy(generateJson: true)
abstract class $TurnStarted implements $$EngineEvent {
  int get turnNumber;
  List<String> get messageIds;
}

@Zorphy(generateJson: true)
abstract class $TurnCompleted implements $$EngineEvent {
  int get turnNumber;
  String get finishReason;
  int get toolCallCount;
}

@Zorphy(generateJson: true)
abstract class $ThinkingDelta implements $$EngineEvent {
  String get content;
  int get deltaIndex;
  bool get isComplete;
}

@Zorphy(generateJson: true)
abstract class $TextDelta implements $$EngineEvent {
  String get content;
  int get deltaIndex;
  bool get isComplete;
}

@Zorphy(generateJson: true)
abstract class $ToolCallStarted implements $$EngineEvent {
  String get toolCallId;
  String get toolName;
  Map<String, dynamic> get arguments;
  int get callIndex;
}

@Zorphy(generateJson: true)
abstract class $ToolCallCompleted implements $$EngineEvent {
  String get toolCallId;
  String get result;
  String? get errorMessage;
  int get durationMs;
}

@Zorphy(generateJson: true)
abstract class $ProviderError implements $$EngineEvent {
  String get errorType;
  String get message;
  bool get isRecoverable;
}

@Zorphy(generateJson: true)
abstract class $SteeringInjected implements $$EngineEvent {
  String get messageId;
  String get content;
  int get injectionPoint;
}

