// GENERATED - DO NOT EDIT
// Generated by zfa for: BranchSummaryEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/branch_summary_entry/branch_summary_entry.dart';
import '../../repositories/branch_summary_entry_repository.dart';

class GetBranchSummaryEntryUseCase
    extends UseCase<BranchSummaryEntry, QueryParams<BranchSummaryEntry>> {
  GetBranchSummaryEntryUseCase(this._repository);

  final BranchSummaryEntryRepository _repository;

  @override
  Future<BranchSummaryEntry> execute(
    QueryParams<BranchSummaryEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
