// GENERATED - DO NOT EDIT
// Generated by zfa for: BranchSummaryEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/branch_summary_entry/branch_summary_entry.dart';
import '../../repositories/branch_summary_entry_repository.dart';

class UpdateBranchSummaryEntryUseCase
    extends
        UseCase<
          BranchSummaryEntry,
          UpdateParams<String, BranchSummaryEntryPatch>
        > {
  UpdateBranchSummaryEntryUseCase(this._repository);

  final BranchSummaryEntryRepository _repository;

  @override
  Future<BranchSummaryEntry> execute(
    UpdateParams<String, BranchSummaryEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
