// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:40:57.671298

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'suite.zorphy.dart';
part 'suite.g.dart';

/// Suite entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Suite {

  String get id;
  String get name;
  List<String> get tasks;
  int get k;
  double? get gateThreshold;
}

