// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentSpec
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_spec/agent_spec.dart';
import '../../repositories/agent_spec_repository.dart';

class GetAgentSpecUseCase extends UseCase<AgentSpec, QueryParams<AgentSpec>> {
  GetAgentSpecUseCase(this._repository);

  final AgentSpecRepository _repository;

  @override
  Future<AgentSpec> execute(
    QueryParams<AgentSpec> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
