// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentSpec
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_spec/agent_spec.dart';
import '../../repositories/agent_spec_repository.dart';

class UpdateAgentSpecUseCase
    extends UseCase<AgentSpec, UpdateParams<String, AgentSpecPatch>> {
  UpdateAgentSpecUseCase(this._repository);

  final AgentSpecRepository _repository;

  @override
  Future<AgentSpec> execute(
    UpdateParams<String, AgentSpecPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
