// GENERATED - DO NOT EDIT
// Generated by zfa for: RepetitionTracker
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/repetition_tracker/repetition_tracker.dart';
import '../../mock/repetition_tracker_mock_data.dart';
import 'repetition_tracker_datasource.dart';

/// Mock data source for RepetitionTracker
class RepetitionTrackerMockDataSource
    with Loggable, FailureHandler
    implements RepetitionTrackerDataSource {
  RepetitionTrackerMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<RepetitionTracker> get(QueryParams<RepetitionTracker> params) async {
    logger.info('Getting RepetitionTracker with params: $params');
    await Future<void>.delayed(_delay);
    final item = RepetitionTrackerMockData.repetitionTrackers.query(params);
    logger.info('Successfully retrieved RepetitionTracker');
    return item;
  }

  @override
  Future<RepetitionTracker> update(
    UpdateParams<String, RepetitionTrackerPatch> params,
  ) async {
    logger.info('Updating RepetitionTracker: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = RepetitionTrackerMockData.sampleRepetitionTracker;
    logger.info('Successfully updated RepetitionTracker');
    return existing;
  }
}

// END GENERATED
