// GENERATED - DO NOT EDIT
// Generated by zfa for: ThinkingLevelChangeEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/thinking_level_change_entry/thinking_level_change_entry.dart';
import '../../repositories/thinking_level_change_entry_repository.dart';

class GetThinkingLevelChangeEntryUseCase
    extends
        UseCase<
          ThinkingLevelChangeEntry,
          QueryParams<ThinkingLevelChangeEntry>
        > {
  GetThinkingLevelChangeEntryUseCase(this._repository);

  final ThinkingLevelChangeEntryRepository _repository;

  @override
  Future<ThinkingLevelChangeEntry> execute(
    QueryParams<ThinkingLevelChangeEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
