// GENERATED - DO NOT EDIT
// Generated by zfa for: ThinkingLevelChangeEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/thinking_level_change_entry/thinking_level_change_entry.dart';
import '../../repositories/thinking_level_change_entry_repository.dart';

class UpdateThinkingLevelChangeEntryUseCase
    extends
        UseCase<
          ThinkingLevelChangeEntry,
          UpdateParams<String, ThinkingLevelChangeEntryPatch>
        > {
  UpdateThinkingLevelChangeEntryUseCase(this._repository);

  final ThinkingLevelChangeEntryRepository _repository;

  @override
  Future<ThinkingLevelChangeEntry> execute(
    UpdateParams<String, ThinkingLevelChangeEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
