// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:41.996408

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'custom_entry.zorphy.dart';
part 'custom_entry.g.dart';

/// CustomEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CustomEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get customType;
  String get payload;
}

