// GENERATED - DO NOT EDIT
// Generated by zfa for: MissionConfig
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/mission_config/mission_config.dart';
import '../../repositories/mission_config_repository.dart';

class GetMissionConfigUseCase
    extends UseCase<MissionConfig, QueryParams<MissionConfig>> {
  GetMissionConfigUseCase(this._repository);

  final MissionConfigRepository _repository;

  @override
  Future<MissionConfig> execute(
    QueryParams<MissionConfig> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
