// GENERATED - DO NOT EDIT
// Generated by zfa for: MissionConfig
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/mission_config/mission_config.dart';
import '../../repositories/mission_config_repository.dart';

class UpdateMissionConfigUseCase
    extends UseCase<MissionConfig, UpdateParams<String, MissionConfigPatch>> {
  UpdateMissionConfigUseCase(this._repository);

  final MissionConfigRepository _repository;

  @override
  Future<MissionConfig> execute(
    UpdateParams<String, MissionConfigPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
