// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:26:50.232485

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'artifact_ref.zorphy.dart';
part 'artifact_ref.g.dart';

/// ArtifactRef entity
@Zorphy(kind: ZorphyKind.valueObject, generateJson: true, generateCompareTo: true)
abstract class $ArtifactRef {

  String get kind;
  String get id;
  String? get uri;
}

