// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:41.697209

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'model_change_entry.zorphy.dart';
part 'model_change_entry.g.dart';

/// ModelChangeEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ModelChangeEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get modelId;
  String get provider;
}

