// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:36.384394

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'compaction_entry.zorphy.dart';
part 'compaction_entry.g.dart';

/// CompactionEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CompactionEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get firstKeptEntryId;
  int get tokensBefore;
  int get tokensAfter;
}

