// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolCallSignature
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_call_signature/tool_call_signature.dart';
import '../../repositories/tool_call_signature_repository.dart';

class GetToolCallSignatureUseCase
    extends UseCase<ToolCallSignature, QueryParams<ToolCallSignature>> {
  GetToolCallSignatureUseCase(this._repository);

  final ToolCallSignatureRepository _repository;

  @override
  Future<ToolCallSignature> execute(
    QueryParams<ToolCallSignature> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
