// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolCallSignature
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_call_signature/tool_call_signature.dart';
import '../../repositories/tool_call_signature_repository.dart';

class UpdateToolCallSignatureUseCase
    extends
        UseCase<
          ToolCallSignature,
          UpdateParams<String, ToolCallSignaturePatch>
        > {
  UpdateToolCallSignatureUseCase(this._repository);

  final ToolCallSignatureRepository _repository;

  @override
  Future<ToolCallSignature> execute(
    UpdateParams<String, ToolCallSignaturePatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
