// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:36.197601

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'turn_record.zorphy.dart';
part 'turn_record.g.dart';

/// TurnRecord entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $TurnRecord {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  int get turnNumber;
  List<String> get messageEntryIds;
  List<String> get toolInvocationEntryIds;
  String get stopReason;
  DateTime get startedAt;
  DateTime get endedAt;
  int get durationMs;
}

