// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/turn_record/turn_record.dart';
import '../../repositories/turn_record_repository.dart';

class CreateTurnRecordUseCase extends UseCase<TurnRecord, TurnRecord> {
  CreateTurnRecordUseCase(this._repository);

  final TurnRecordRepository _repository;

  @override
  Future<TurnRecord> execute(
    TurnRecord params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
