// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnRecord
import 'package:zuraffa/zuraffa.dart';

import '../../repositories/turn_record_repository.dart';

class DeleteTurnRecordUseCase extends CompletableUseCase<DeleteParams<String>> {
  DeleteTurnRecordUseCase(this._repository);

  final TurnRecordRepository _repository;

  @override
  Future<void> execute(
    DeleteParams<String> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.delete(params);
  }
}

// END GENERATED
