// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/turn_record/turn_record.dart';
import '../../repositories/turn_record_repository.dart';

class GetTurnRecordListUseCase
    extends UseCase<List<TurnRecord>, ListQueryParams<TurnRecord>> {
  GetTurnRecordListUseCase(this._repository);

  final TurnRecordRepository _repository;

  @override
  Future<List<TurnRecord>> execute(
    ListQueryParams<TurnRecord> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList(params);
  }
}

// END GENERATED
