// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnRecord
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/turn_record/turn_record.dart';
import '../../repositories/turn_record_repository.dart';

class UpdateTurnRecordUseCase
    extends UseCase<TurnRecord, UpdateParams<String, TurnRecordPatch>> {
  UpdateTurnRecordUseCase(this._repository);

  final TurnRecordRepository _repository;

  @override
  Future<TurnRecord> execute(
    UpdateParams<String, TurnRecordPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
