// GENERATED - DO NOT EDIT
// Generated by zfa for: ApprovalRequest
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/approval_request/approval_request.dart';
import '../../repositories/approval_request_repository.dart';

class GetApprovalRequestUseCase
    extends UseCase<ApprovalRequest, QueryParams<ApprovalRequest>> {
  GetApprovalRequestUseCase(this._repository);

  final ApprovalRequestRepository _repository;

  @override
  Future<ApprovalRequest> execute(
    QueryParams<ApprovalRequest> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
