// GENERATED - DO NOT EDIT
// Generated by zfa for: ApprovalRequest
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/approval_request/approval_request.dart';
import '../../repositories/approval_request_repository.dart';

class UpdateApprovalRequestUseCase
    extends
        UseCase<ApprovalRequest, UpdateParams<String, ApprovalRequestPatch>> {
  UpdateApprovalRequestUseCase(this._repository);

  final ApprovalRequestRepository _repository;

  @override
  Future<ApprovalRequest> execute(
    UpdateParams<String, ApprovalRequestPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
