// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactRef
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact_ref/artifact_ref.dart';
import '../../mock/artifact_ref_mock_data.dart';
import 'artifact_ref_datasource.dart';

/// Mock data source for ArtifactRef
class ArtifactRefMockDataSource
    with Loggable, FailureHandler
    implements ArtifactRefDataSource {
  ArtifactRefMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ArtifactRef> get(QueryParams<ArtifactRef> params) async {
    logger.info('Getting ArtifactRef with params: $params');
    await Future<void>.delayed(_delay);
    final item = ArtifactRefMockData.artifactRefs.query(params);
    logger.info('Successfully retrieved ArtifactRef');
    return item;
  }

  @override
  Future<ArtifactRef> update(
    UpdateParams<String, ArtifactRefPatch> params,
  ) async {
    logger.info('Updating ArtifactRef: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = ArtifactRefMockData.sampleArtifactRef;
    logger.info('Successfully updated ArtifactRef');
    return existing;
  }

  @override
  Future<ArtifactRef> toggle(
    ToggleParams<String, Field<ArtifactRef, dynamic>> params,
  ) async {
    logger.info('Toggling ArtifactRef: ${params.id} on field ${params.field}');
    await Future<void>.delayed(_delay);
    final existing = ArtifactRefMockData.sampleArtifactRef;
    logger.info('Successfully toggled ArtifactRef');
    return existing;
  }
}

// END GENERATED
