// GENERATED - DO NOT EDIT
// Generated by zfa for: LabelEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/label_entry/label_entry.dart';
import '../../repositories/label_entry_repository.dart';

class GetLabelEntryUseCase
    extends UseCase<LabelEntry, QueryParams<LabelEntry>> {
  GetLabelEntryUseCase(this._repository);

  final LabelEntryRepository _repository;

  @override
  Future<LabelEntry> execute(
    QueryParams<LabelEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
