// GENERATED - DO NOT EDIT
// Generated by zfa for: LabelEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/label_entry/label_entry.dart';
import '../../repositories/label_entry_repository.dart';

class UpdateLabelEntryUseCase
    extends UseCase<LabelEntry, UpdateParams<String, LabelEntryPatch>> {
  UpdateLabelEntryUseCase(this._repository);

  final LabelEntryRepository _repository;

  @override
  Future<LabelEntry> execute(
    UpdateParams<String, LabelEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
