// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:36.263717

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'tool_invocation_record.zorphy.dart';
part 'tool_invocation_record.g.dart';

/// ToolInvocationRecord entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ToolInvocationRecord {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get toolCallId;
  String get toolName;
  String? get resultEntryId;
  bool get isError;
  int get durationMs;
}

