// GENERATED - DO NOT EDIT
// Generated by zfa for: ClientHealth
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/client_health/client_health.dart';
import '../../repositories/client_health_repository.dart';

class GetClientHealthUseCase
    extends UseCase<ClientHealth, QueryParams<ClientHealth>> {
  GetClientHealthUseCase(this._repository);

  final ClientHealthRepository _repository;

  @override
  Future<ClientHealth> execute(
    QueryParams<ClientHealth> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
