// GENERATED - DO NOT EDIT
// Generated by zfa for: ClientHealth
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/client_health/client_health.dart';
import '../../repositories/client_health_repository.dart';

class UpdateClientHealthUseCase
    extends UseCase<ClientHealth, UpdateParams<String, ClientHealthPatch>> {
  UpdateClientHealthUseCase(this._repository);

  final ClientHealthRepository _repository;

  @override
  Future<ClientHealth> execute(
    UpdateParams<String, ClientHealthPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
