// GENERATED - DO NOT EDIT
// Generated by zfa for: RepetitionTracker
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/repetition_tracker/repetition_tracker.dart';
import '../../repositories/repetition_tracker_repository.dart';

class GetRepetitionTrackerUseCase
    extends UseCase<RepetitionTracker, QueryParams<RepetitionTracker>> {
  GetRepetitionTrackerUseCase(this._repository);

  final RepetitionTrackerRepository _repository;

  @override
  Future<RepetitionTracker> execute(
    QueryParams<RepetitionTracker> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
