// GENERATED - DO NOT EDIT
// Generated by zfa for: RepetitionTracker
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/repetition_tracker/repetition_tracker.dart';
import '../../repositories/repetition_tracker_repository.dart';

class UpdateRepetitionTrackerUseCase
    extends
        UseCase<
          RepetitionTracker,
          UpdateParams<String, RepetitionTrackerPatch>
        > {
  UpdateRepetitionTrackerUseCase(this._repository);

  final RepetitionTrackerRepository _repository;

  @override
  Future<RepetitionTracker> execute(
    UpdateParams<String, RepetitionTrackerPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
