// Auto-generated by Zorphy
// Generated at: 2026-08-21T15:21:47.409032

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'enums.zorphy.dart';
part 'enums.g.dart';

/// Enums entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Enums {

  String get id;
  List<String> get values;
  String? get description;
}

