// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:30:41.902974

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'label_entry.zorphy.dart';
part 'label_entry.g.dart';

/// LabelEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $LabelEntry {

  String get id;
  String? get parentId;
  DateTime get timestamp;
  String get label;
}

