// Auto-generated by Zorphy
// Generated at: 2026-08-18T20:26:50.308646

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'model.zorphy.dart';
part 'model.g.dart';

/// Model entity
@Zorphy(kind: ZorphyKind.valueObject, generateJson: true, generateCompareTo: true)
abstract class $Model {

  String get provider;
  String get modelId;
  int get contextWindow;
}

