// GENERATED - DO NOT EDIT
// Generated by zfa for: DispatchTool
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/dispatch_tool/dispatch_tool.dart';
import '../../repositories/dispatch_tool_repository.dart';

class GetDispatchToolUseCase
    extends UseCase<DispatchTool, QueryParams<DispatchTool>> {
  GetDispatchToolUseCase(this._repository);

  final DispatchToolRepository _repository;

  @override
  Future<DispatchTool> execute(
    QueryParams<DispatchTool> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
