// GENERATED - DO NOT EDIT
// Generated by zfa for: DispatchTool
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/dispatch_tool/dispatch_tool.dart';
import '../../repositories/dispatch_tool_repository.dart';

class UpdateDispatchToolUseCase
    extends UseCase<DispatchTool, UpdateParams<String, DispatchToolPatch>> {
  UpdateDispatchToolUseCase(this._repository);

  final DispatchToolRepository _repository;

  @override
  Future<DispatchTool> execute(
    UpdateParams<String, DispatchToolPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
