// GENERATED - DO NOT EDIT
// Generated by zfa for: SubAgentType
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/sub_agent_type/sub_agent_type.dart';
import '../../repositories/sub_agent_type_repository.dart';

class GetSubAgentTypeUseCase
    extends UseCase<SubAgentType, QueryParams<SubAgentType>> {
  GetSubAgentTypeUseCase(this._repository);

  final SubAgentTypeRepository _repository;

  @override
  Future<SubAgentType> execute(
    QueryParams<SubAgentType> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
