// GENERATED - DO NOT EDIT
// Generated by zfa for: SubAgentType
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/sub_agent_type/sub_agent_type.dart';
import '../../repositories/sub_agent_type_repository.dart';

class UpdateSubAgentTypeUseCase
    extends UseCase<SubAgentType, UpdateParams<String, SubAgentTypePatch>> {
  UpdateSubAgentTypeUseCase(this._repository);

  final SubAgentTypeRepository _repository;

  @override
  Future<SubAgentType> execute(
    UpdateParams<String, SubAgentTypePatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
