// GENERATED - DO NOT EDIT
// Generated by zfa for: Model
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/model/model.dart';
import '../../repositories/model_repository.dart';

class GetModelUseCase extends UseCase<Model, QueryParams<Model>> {
  GetModelUseCase(this._repository);

  final ModelRepository _repository;

  @override
  Future<Model> execute(
    QueryParams<Model> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
