// GENERATED - DO NOT EDIT
// Generated by zfa for: Model
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/model/model.dart';
import '../../repositories/model_repository.dart';

class UpdateModelUseCase
    extends UseCase<Model, UpdateParams<String, ModelPatch>> {
  UpdateModelUseCase(this._repository);

  final ModelRepository _repository;

  @override
  Future<Model> execute(
    UpdateParams<String, ModelPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
