// GENERATED - DO NOT EDIT
// Generated by zfa for: AgentTool
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/agent_tool/agent_tool.dart';
import '../../mock/agent_tool_mock_data.dart';
import 'agent_tool_datasource.dart';

/// Mock data source for AgentTool
class AgentToolMockDataSource
    with Loggable, FailureHandler
    implements AgentToolDataSource {
  AgentToolMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<AgentTool> get(QueryParams<AgentTool> params) async {
    logger.info('Getting AgentTool with params: $params');
    await Future<void>.delayed(_delay);
    final item = AgentToolMockData.agentTools.query(params);
    logger.info('Successfully retrieved AgentTool');
    return item;
  }

  @override
  Future<AgentTool> update(UpdateParams<String, AgentToolPatch> params) async {
    logger.info('Updating AgentTool: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = AgentToolMockData.sampleAgentTool;
    logger.info('Successfully updated AgentTool');
    return existing;
  }

  @override
  Future<AgentTool> toggle(
    ToggleParams<String, Field<AgentTool, dynamic>> params,
  ) async {
    logger.info('Toggling AgentTool: ${params.id} on field ${params.field}');
    await Future<void>.delayed(_delay);
    final existing = AgentToolMockData.sampleAgentTool;
    logger.info('Successfully toggled AgentTool');
    return existing;
  }
}

// END GENERATED
