// Auto-generated by Zorphy
// Generated at: 2026-08-20T16:54:00.389376

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'artifact_service_config.zorphy.dart';
part 'artifact_service_config.g.dart';

/// ArtifactServiceConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ArtifactServiceConfig {

  int get thresholdBytes;
}

