// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:35:24.129124

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';
import '../client_health/client_health.dart';

part 'fallback_chain.zorphy.dart';
part 'fallback_chain.g.dart';

/// FallbackChain entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $FallbackChain {

  String get id;
  List<String> get providerOrder;
  int get maxConsecutiveFailures;
  int get cooldownMs;
  String get policyMode;
  List<$ClientHealth> get breakerStates;
  int get lastProviderIndex;
}

