// Auto-generated by Zorphy
// Generated at: 2026-08-27T16:37:08.371432

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'golden_mission.zorphy.dart';
part 'golden_mission.g.dart';

/// GoldenMission entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $GoldenMission {

  String get id;
  String get name;
  Map<String, dynamic> get cassette;
  String get taskDefinition;
  List<String> get graderBindings;
}

