// GENERATED - DO NOT EDIT
// Generated by zfa for: Artifact
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact/artifact.dart';
import '../../repositories/artifact_repository.dart';

class GetArtifactUseCase extends UseCase<Artifact, QueryParams<Artifact>> {
  GetArtifactUseCase(this._repository);

  final ArtifactRepository _repository;

  @override
  Future<Artifact> execute(
    QueryParams<Artifact> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
