// GENERATED - DO NOT EDIT
// Generated by zfa for: Artifact
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact/artifact.dart';
import '../../repositories/artifact_repository.dart';

class UpdateArtifactUseCase
    extends UseCase<Artifact, UpdateParams<String, ArtifactPatch>> {
  UpdateArtifactUseCase(this._repository);

  final ArtifactRepository _repository;

  @override
  Future<Artifact> execute(
    UpdateParams<String, ArtifactPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
