// GENERATED - DO NOT EDIT
// Generated by zfa for: StopPolicy
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/stop_policy/stop_policy.dart';
import '../../mock/stop_policy_mock_data.dart';
import 'stop_policy_datasource.dart';

/// Mock data source for StopPolicy
class StopPolicyMockDataSource
    with Loggable, FailureHandler
    implements StopPolicyDataSource {
  StopPolicyMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<StopPolicy> get(QueryParams<StopPolicy> params) async {
    logger.info('Getting StopPolicy with params: $params');
    await Future.delayed(_delay);
    final item = StopPolicyMockData.stopPolicys.query(params);
    logger.info('Successfully retrieved StopPolicy');
    return item;
  }

  @override
  Future<StopPolicy> update(
    UpdateParams<String, StopPolicyPatch> params,
  ) async {
    logger.info('Updating StopPolicy: ${params.id}');
    await Future.delayed(_delay);
    final existing = StopPolicyMockData.sampleStopPolicy;
    logger.info('Successfully updated StopPolicy');
    return existing;
  }

  @override
  Future<StopPolicy> toggle(
    ToggleParams<String, Field<StopPolicy, dynamic>> params,
  ) async {
    logger.info('Toggling StopPolicy: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = StopPolicyMockData.sampleStopPolicy;
    logger.info('Successfully toggled StopPolicy');
    return existing;
  }
}

// END GENERATED
