// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnContext
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/turn_context/turn_context.dart';
import '../../repositories/turn_context_repository.dart';

class GetTurnContextUseCase
    extends UseCase<TurnContext, QueryParams<TurnContext>> {
  GetTurnContextUseCase(this._repository);

  final TurnContextRepository _repository;

  @override
  Future<TurnContext> execute(
    QueryParams<TurnContext> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
