// GENERATED - DO NOT EDIT
// Generated by zfa for: TurnContext
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/turn_context/turn_context.dart';
import '../../repositories/turn_context_repository.dart';

class UpdateTurnContextUseCase
    extends UseCase<TurnContext, UpdateParams<String, TurnContextPatch>> {
  UpdateTurnContextUseCase(this._repository);

  final TurnContextRepository _repository;

  @override
  Future<TurnContext> execute(
    UpdateParams<String, TurnContextPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
