// Auto-generated by Zorphy
// Generated at: 2026-08-20T14:45:57.419951

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';
import '../enums/index.dart';

part 'agent_tool.zorphy.dart';
part 'agent_tool.g.dart';

/// AgentTool entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $AgentTool {

  String get id;
  String get name;
  String get description;
  Map<String, dynamic> get inputSchema;
  RiskTier get riskTier;
  ExecutionMode get executionMode;
  ToolSource get source;
  String? get transportBinding;
}

