// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/compaction_entry/compaction_entry.dart';
import '../../repositories/compaction_entry_repository.dart';

class GetCompactionEntryUseCase
    extends UseCase<CompactionEntry, QueryParams<CompactionEntry>> {
  GetCompactionEntryUseCase(this._repository);

  final CompactionEntryRepository _repository;

  @override
  Future<CompactionEntry> execute(
    QueryParams<CompactionEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
