// GENERATED - DO NOT EDIT
// Generated by zfa for: CompactionEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/compaction_entry/compaction_entry.dart';
import '../../repositories/compaction_entry_repository.dart';

class UpdateCompactionEntryUseCase
    extends
        UseCase<CompactionEntry, UpdateParams<String, CompactionEntryPatch>> {
  UpdateCompactionEntryUseCase(this._repository);

  final CompactionEntryRepository _repository;

  @override
  Future<CompactionEntry> execute(
    UpdateParams<String, CompactionEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
