// Auto-generated by Zorphy
// Generated at: 2026-08-21T14:38:11.943046

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'agent_spec.zorphy.dart';
part 'agent_spec.g.dart';

/// AgentSpec entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $AgentSpec {

  String get id;
  List<String> get tools;
  List<String> get subagents;
  String get budget;
  String get systemPrompt;
  String get riskTier;
  @JsonKey(name: 'extends')
  String get extendsSpec;
}

