// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/custom_entry/custom_entry.dart';
import '../../repositories/custom_entry_repository.dart';

class GetCustomEntryUseCase
    extends UseCase<CustomEntry, QueryParams<CustomEntry>> {
  GetCustomEntryUseCase(this._repository);

  final CustomEntryRepository _repository;

  @override
  Future<CustomEntry> execute(
    QueryParams<CustomEntry> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
