// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/custom_entry/custom_entry.dart';
import '../../repositories/custom_entry_repository.dart';

class UpdateCustomEntryUseCase
    extends UseCase<CustomEntry, UpdateParams<String, CustomEntryPatch>> {
  UpdateCustomEntryUseCase(this._repository);

  final CustomEntryRepository _repository;

  @override
  Future<CustomEntry> execute(
    UpdateParams<String, CustomEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
