// GENERATED - DO NOT EDIT
// Generated by zfa for: EngineEvent
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/engine_event/engine_event.dart';
import '../../repositories/engine_event_repository.dart';

class GetEngineEventUseCase
    extends UseCase<EngineEvent, QueryParams<EngineEvent>> {
  GetEngineEventUseCase(this._repository);

  final EngineEventRepository _repository;

  @override
  Future<EngineEvent> execute(
    QueryParams<EngineEvent> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
