// GENERATED - DO NOT EDIT
// Generated by zfa for: EngineEvent
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/engine_event/engine_event.dart';
import '../../repositories/engine_event_repository.dart';

class UpdateEngineEventUseCase
    extends UseCase<EngineEvent, UpdateParams<String, EngineEventPatch>> {
  UpdateEngineEventUseCase(this._repository);

  final EngineEventRepository _repository;

  @override
  Future<EngineEvent> execute(
    UpdateParams<String, EngineEventPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
