// GENERATED - DO NOT EDIT
// Generated by zfa for: ToolCallSignature
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/tool_call_signature/tool_call_signature.dart';
import '../../mock/tool_call_signature_mock_data.dart';
import 'tool_call_signature_datasource.dart';

/// Mock data source for ToolCallSignature
class ToolCallSignatureMockDataSource
    with Loggable, FailureHandler
    implements ToolCallSignatureDataSource {
  ToolCallSignatureMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ToolCallSignature> get(QueryParams<ToolCallSignature> params) async {
    logger.info('Getting ToolCallSignature with params: $params');
    await Future.delayed(_delay);
    final item = ToolCallSignatureMockData.toolCallSignatures.query(params);
    logger.info('Successfully retrieved ToolCallSignature');
    return item;
  }

  @override
  Future<ToolCallSignature> update(
    UpdateParams<String, ToolCallSignaturePatch> params,
  ) async {
    logger.info('Updating ToolCallSignature: ${params.id}');
    await Future.delayed(_delay);
    final existing = ToolCallSignatureMockData.sampleToolCallSignature;
    logger.info('Successfully updated ToolCallSignature');
    return existing;
  }

  @override
  Future<ToolCallSignature> toggle(
    ToggleParams<String, Field<ToolCallSignature, dynamic>> params,
  ) async {
    logger.info(
      'Toggling ToolCallSignature: ${params.id} on field ${params.field}',
    );
    await Future.delayed(_delay);
    final existing = ToolCallSignatureMockData.sampleToolCallSignature;
    logger.info('Successfully toggled ToolCallSignature');
    return existing;
  }
}

// END GENERATED
