// GENERATED - DO NOT EDIT
// Generated by zfa for: ArtifactServiceConfig
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/artifact_service_config/artifact_service_config.dart';
import '../../repositories/artifact_service_config_repository.dart';

class UpdateArtifactServiceConfigUseCase
    extends
        UseCase<
          ArtifactServiceConfig,
          UpdateParams<String, ArtifactServiceConfigPatch>
        > {
  UpdateArtifactServiceConfigUseCase(this._repository);

  final ArtifactServiceConfigRepository _repository;

  @override
  Future<ArtifactServiceConfig> execute(
    UpdateParams<String, ArtifactServiceConfigPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
