// GENERATED - DO NOT EDIT
// Generated by zfa for: ModelChangeEntry
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/model_change_entry/model_change_entry.dart';
import '../../repositories/model_change_entry_repository.dart';

class UpdateModelChangeEntryUseCase
    extends
        UseCase<ModelChangeEntry, UpdateParams<String, ModelChangeEntryPatch>> {
  UpdateModelChangeEntryUseCase(this._repository);

  final ModelChangeEntryRepository _repository;

  @override
  Future<ModelChangeEntry> execute(
    UpdateParams<String, ModelChangeEntryPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
